use serde::{Deserialize, Serialize};
use crate::complex_datatypes::{Address, Age, Annotation, Attachment, CodeableConcept};

/// Bootstrap representation of a FHIR Extension.
///
/// Extensions provide a mechanism for conveying additional information not
/// captured in the base definition of a resource or data type. This bootstrap
/// version includes the most common value types needed for parsing StructureDefinitions.
///
/// Note: This is a simplified version used only for code generation. The full
/// Extension type with all possible value types is generated by the code generator.
#[derive(Debug, Serialize, Deserialize)]
pub struct Extension {
    pub id: Option<String>,
    pub extension: Option<Vec<Extension>>,
    pub url: String,
    #[serde(rename = "valueBase64Binary")]
    pub value_base64_binary: Option<String>,
    #[serde(rename = "valueBoolean")]
    pub value_boolean: Option<bool>,
    #[serde(rename = "valueCanonical")]
    pub value_canonical: Option<String>,
    #[serde(rename = "valueCode")]
    pub value_code: Option<String>,
    #[serde(rename = "valueDate")]
    pub value_date: Option<String>,
    #[serde(rename = "valueDateTime")]
    pub value_date_time: Option<String>,
    #[serde(rename = "valueDecimal")]
    pub value_decimal: Option<String>,
    #[serde(rename = "valueId")]
    pub value_id: Option<String>,
    #[serde(rename = "valueInstant")]
    pub value_instant: Option<String>,
    #[serde(rename = "valueInteger")]
    pub value_integer: Option<i32>,
    #[serde(rename = "valueInteger64")]
    pub value_integer64: Option<i64>,
    #[serde(rename = "valueMarkdown")]
    pub value_markdown: Option<String>,
    #[serde(rename = "valueOid")]
    pub value_oid: Option<String>,
    #[serde(rename = "valuePositiveInt")]
    pub value_positive_int: Option<u32>,
    #[serde(rename = "valueString")]
    pub value_string: Option<String>,
    #[serde(rename = "valueTime")]
    pub value_time: Option<String>,
    #[serde(rename = "valueUnsignedInt")]
    pub value_unsigned_int: Option<u32>,
    #[serde(rename = "valueUri")]
    pub value_uri: Option<String>,
    #[serde(rename = "valueUrl")]
    pub value_url: Option<String>,
    #[serde(rename = "valueUuid")]
    pub value_uid: Option<String>,
    #[serde(rename = "valueAddress")]
    pub value_address: Option<Address>,
    #[serde(rename = "valueAge")]
    pub value_age: Option<Age>,
    #[serde(rename = "valueAnnotation")]
    pub value_annotation: Option<Annotation>,
    #[serde(rename = "valueAttachment")]
    pub value_attachment: Option<Attachment>,
    #[serde(rename = "valueCodeableConcept")]
    pub value_codeable_concept: Option<CodeableConcept>,
    /*    pub valueCodeableReference: Option<CodeableReference>,
        pub valueCoding: Option<Coding>,
    valueContactPoint: ContactPoint
    valueCount: Count
    valueDistance: Distance
    valueDuration: Duration
    valueHumanName: HumanName
    valueIdentifier: Identifier
    valueMoney: Money
    valuePeriod: Period
    valueQuantity: Quantity
    valueRange: Range
    valueRatio: Ratio
    valueRatioRange: RatioRange
    valueReference: Reference - a reference to another resource
    valueSampledData: SampledData
    valueSignature: Signature
    valueTiming: Timing
    valueContactDetail: ContactDetail
    valueDataRequirement: DataRequirement
    valueExpression: Expression
    valueParameterDefinition: ParameterDefinition
    valueRelatedArtifact: RelatedArtifact
    valueTriggerDefinition: TriggerDefinition
    valueUsageContext: UsageContext
    valueAvailability: Availability
    valueExtendedContactDetail: ExtendedContactDetail
    valueDosage: Dosage
    valueMeta: Meta
    */
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Element {
    pub id: Option<String>,
    pub extension: Option<Vec<Extension>>,
}
