// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: AssertionResponseTypes
///Canonical URL: http://hl7.org/fhir/ValueSet/assert-response-code-types
///Version: 5.0.0
///Title: Assertion Response Types
///Status: draft
///The type of response code to use for assertion.
///Compose includes 44 explicit concept codes
///Includes systems:
///- http://hl7.org/fhir/assert-response-code-types
pub struct AssertionResponseTypes;
impl AssertionResponseTypes {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/assert-response-code-types";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://hl7.org/fhir/assert-response-code-types"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://hl7.org/fhir/assert-response-code-types", "continue"),
            ("http://hl7.org/fhir/assert-response-code-types", "switchingProtocols"),
            ("http://hl7.org/fhir/assert-response-code-types", "okay"),
            ("http://hl7.org/fhir/assert-response-code-types", "created"),
            ("http://hl7.org/fhir/assert-response-code-types", "accepted"),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "nonAuthoritativeInformation",
            ),
            ("http://hl7.org/fhir/assert-response-code-types", "noContent"),
            ("http://hl7.org/fhir/assert-response-code-types", "resetContent"),
            ("http://hl7.org/fhir/assert-response-code-types", "partialContent"),
            ("http://hl7.org/fhir/assert-response-code-types", "multipleChoices"),
            ("http://hl7.org/fhir/assert-response-code-types", "movedPermanently"),
            ("http://hl7.org/fhir/assert-response-code-types", "found"),
            ("http://hl7.org/fhir/assert-response-code-types", "seeOther"),
            ("http://hl7.org/fhir/assert-response-code-types", "notModified"),
            ("http://hl7.org/fhir/assert-response-code-types", "useProxy"),
            ("http://hl7.org/fhir/assert-response-code-types", "temporaryRedirect"),
            ("http://hl7.org/fhir/assert-response-code-types", "permanentRedirect"),
            ("http://hl7.org/fhir/assert-response-code-types", "badRequest"),
            ("http://hl7.org/fhir/assert-response-code-types", "unauthorized"),
            ("http://hl7.org/fhir/assert-response-code-types", "paymentRequired"),
            ("http://hl7.org/fhir/assert-response-code-types", "forbidden"),
            ("http://hl7.org/fhir/assert-response-code-types", "notFound"),
            ("http://hl7.org/fhir/assert-response-code-types", "methodNotAllowed"),
            ("http://hl7.org/fhir/assert-response-code-types", "notAcceptable"),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "proxyAuthenticationRequired",
            ),
            ("http://hl7.org/fhir/assert-response-code-types", "requestTimeout"),
            ("http://hl7.org/fhir/assert-response-code-types", "conflict"),
            ("http://hl7.org/fhir/assert-response-code-types", "gone"),
            ("http://hl7.org/fhir/assert-response-code-types", "lengthRequired"),
            ("http://hl7.org/fhir/assert-response-code-types", "preconditionFailed"),
            ("http://hl7.org/fhir/assert-response-code-types", "contentTooLarge"),
            ("http://hl7.org/fhir/assert-response-code-types", "uriTooLong"),
            ("http://hl7.org/fhir/assert-response-code-types", "unsupportedMediaType"),
            ("http://hl7.org/fhir/assert-response-code-types", "rangeNotSatisfiable"),
            ("http://hl7.org/fhir/assert-response-code-types", "expectationFailed"),
            ("http://hl7.org/fhir/assert-response-code-types", "misdirectedRequest"),
            ("http://hl7.org/fhir/assert-response-code-types", "unprocessableContent"),
            ("http://hl7.org/fhir/assert-response-code-types", "upgradeRequired"),
            ("http://hl7.org/fhir/assert-response-code-types", "internalServerError"),
            ("http://hl7.org/fhir/assert-response-code-types", "notImplemented"),
            ("http://hl7.org/fhir/assert-response-code-types", "badGateway"),
            ("http://hl7.org/fhir/assert-response-code-types", "serviceUnavailable"),
            ("http://hl7.org/fhir/assert-response-code-types", "gatewayTimeout"),
            ("http://hl7.org/fhir/assert-response-code-types", "httpVersionNotSupported"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "accepted",
                Some("Accepted"),
                Some("Response code is 202."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "badGateway",
                Some("Bad Gateway"),
                Some("Response code is 502."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "badRequest",
                Some("Bad Request"),
                Some("Response code is 400."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "conflict",
                Some("Conflict"),
                Some("Response code is 409."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "contentTooLarge",
                Some("Content Too Large"),
                Some("Response code is 413."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "continue",
                Some("Continue"),
                Some("Response code is 100."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "created",
                Some("Created"),
                Some("Response code is 201."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "expectationFailed",
                Some("Expectation Failed"),
                Some("Response code is 417."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "forbidden",
                Some("Forbidden"),
                Some("Response code is 403."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "found",
                Some("Found"),
                Some("Response code is 302."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "gatewayTimeout",
                Some("Gateway Timeout"),
                Some("Response code is 504."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "gone",
                Some("Gone"),
                Some("Response code is 410."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "httpVersionNotSupported",
                Some("HTTP Version Not Supported"),
                Some("Response code is 505."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "internalServerError",
                Some("Internal Server Error"),
                Some("Response code is 500."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "lengthRequired",
                Some("Length Required"),
                Some("Response code is 411."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "methodNotAllowed",
                Some("Method Not Allowed"),
                Some("Response code is 405."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "misdirectedRequest",
                Some("Misdirected Request"),
                Some("Response code is 421."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "movedPermanently",
                Some("Moved Permanently"),
                Some("Response code is 301."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "multipleChoices",
                Some("Multiple Choices"),
                Some("Response code is 300."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "noContent",
                Some("No Content"),
                Some("Response code is 204."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "nonAuthoritativeInformation",
                Some("Non-Authoritative Information"),
                Some("Response code is 203."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "notAcceptable",
                Some("Not Acceptable"),
                Some("Response code is 406."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "notFound",
                Some("Not Found"),
                Some("Response code is 404."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "notImplemented",
                Some("Not Implemented"),
                Some("Response code is 501."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "notModified",
                Some("Not Modified"),
                Some("Response code is 304."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "okay",
                Some("OK"),
                Some("Response code is 200."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "partialContent",
                Some("Partial Content"),
                Some("Response code is 206."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "paymentRequired",
                Some("Payment Required"),
                Some("Response code is 402."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "permanentRedirect",
                Some("Permanent Redirect"),
                Some("Response code is 308."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "preconditionFailed",
                Some("Precondition Failed"),
                Some("Response code is 412."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "proxyAuthenticationRequired",
                Some("Proxy Authentication Required"),
                Some("Response code is 407."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "rangeNotSatisfiable",
                Some("Range Not Satisfiable"),
                Some("Response code is 416."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "requestTimeout",
                Some("Request Timeout"),
                Some("Response code is 408."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "resetContent",
                Some("Reset Content"),
                Some("Response code is 205."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "seeOther",
                Some("See Other"),
                Some("Response code is 303."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "serviceUnavailable",
                Some("Service Unavailable"),
                Some("Response code is 503."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "switchingProtocols",
                Some("Switching Protocols"),
                Some("Response code is 101."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "temporaryRedirect",
                Some("Temporary Redirect"),
                Some("Response code is 307."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "unauthorized",
                Some("Unauthorized"),
                Some("Response code is 401."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "unprocessableContent",
                Some("Unprocessable Content"),
                Some("Response code is 422."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "unsupportedMediaType",
                Some("Unsupported Media Type"),
                Some("Response code is 415."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "upgradeRequired",
                Some("Upgrade Required"),
                Some("Response code is 426."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "uriTooLong",
                Some("URI Too Long"),
                Some("Response code is 414."),
            ),
            (
                "http://hl7.org/fhir/assert-response-code-types",
                "useProxy",
                Some("Use Proxy"),
                Some("Response code is 305."),
            ),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            "http://hl7.org/fhir/assert-response-code-types" => {
                super::super::code_systems::assert_response_code_types::AssertionResponseTypes::try_from_code(
                        code,
                    )
                    .is_ok()
            }
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for AssertionResponseTypes {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for AssertionResponseTypes {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for AssertionResponseTypes {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

