// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: PracticeSettingCodeValueSet
///Canonical URL: http://hl7.org/fhir/ValueSet/c80-practice-codes
///Version: 5.0.0
///Title: Practice Setting Code Value Set
///Status: active
///This is the code representing the clinical specialty of the clinician or provider who    interacted with, treated, or provided a service to/for the patient. The value set used    for clinical specialty has been limited by HITSP to the value set reproduced from HITSP    C80 Table 2-149 Clinical Specialty Value Set Definition.
///Compose includes 117 explicit concept codes
///Includes systems:
///- http://snomed.info/sct
pub struct PracticeSettingCodeValueSet;
impl PracticeSettingCodeValueSet {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/c80-practice-codes";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://snomed.info/sct"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://snomed.info/sct", "408467006"),
            ("http://snomed.info/sct", "394577000"),
            ("http://snomed.info/sct", "394578005"),
            ("http://snomed.info/sct", "421661004"),
            ("http://snomed.info/sct", "408462000"),
            ("http://snomed.info/sct", "394579002"),
            ("http://snomed.info/sct", "394804000"),
            ("http://snomed.info/sct", "394580004"),
            ("http://snomed.info/sct", "394803006"),
            ("http://snomed.info/sct", "408480009"),
            ("http://snomed.info/sct", "408454008"),
            ("http://snomed.info/sct", "394809005"),
            ("http://snomed.info/sct", "394592004"),
            ("http://snomed.info/sct", "394600006"),
            ("http://snomed.info/sct", "394601005"),
            ("http://snomed.info/sct", "394581000"),
            ("http://snomed.info/sct", "408478003"),
            ("http://snomed.info/sct", "394812008"),
            ("http://snomed.info/sct", "408444009"),
            ("http://snomed.info/sct", "394582007"),
            ("http://snomed.info/sct", "408475000"),
            ("http://snomed.info/sct", "410005002"),
            ("http://snomed.info/sct", "394583002"),
            ("http://snomed.info/sct", "419772000"),
            ("http://snomed.info/sct", "394584008"),
            ("http://snomed.info/sct", "408443003"),
            ("http://snomed.info/sct", "394802001"),
            ("http://snomed.info/sct", "394915009"),
            ("http://snomed.info/sct", "394814009"),
            ("http://snomed.info/sct", "394808002"),
            ("http://snomed.info/sct", "394811001"),
            ("http://snomed.info/sct", "408446006"),
            ("http://snomed.info/sct", "394586005"),
            ("http://snomed.info/sct", "394916005"),
            ("http://snomed.info/sct", "408472002"),
            ("http://snomed.info/sct", "394597005"),
            ("http://snomed.info/sct", "394598000"),
            ("http://snomed.info/sct", "394807007"),
            ("http://snomed.info/sct", "419192003"),
            ("http://snomed.info/sct", "408468001"),
            ("http://snomed.info/sct", "394593009"),
            ("http://snomed.info/sct", "394813003"),
            ("http://snomed.info/sct", "410001006"),
            ("http://snomed.info/sct", "394589003"),
            ("http://snomed.info/sct", "394591006"),
            ("http://snomed.info/sct", "394599008"),
            ("http://snomed.info/sct", "394649004"),
            ("http://snomed.info/sct", "408470005"),
            ("http://snomed.info/sct", "394585009"),
            ("http://snomed.info/sct", "394821009"),
            ("http://snomed.info/sct", "422191005"),
            ("http://snomed.info/sct", "394594003"),
            ("http://snomed.info/sct", "416304004"),
            ("http://snomed.info/sct", "418960008"),
            ("http://snomed.info/sct", "394882004"),
            ("http://snomed.info/sct", "394806003"),
            ("http://snomed.info/sct", "394588006"),
            ("http://snomed.info/sct", "408459003"),
            ("http://snomed.info/sct", "394607009"),
            ("http://snomed.info/sct", "419610006"),
            ("http://snomed.info/sct", "418058008"),
            ("http://snomed.info/sct", "420208008"),
            ("http://snomed.info/sct", "418652005"),
            ("http://snomed.info/sct", "418535003"),
            ("http://snomed.info/sct", "418862001"),
            ("http://snomed.info/sct", "419365004"),
            ("http://snomed.info/sct", "418002000"),
            ("http://snomed.info/sct", "419983000"),
            ("http://snomed.info/sct", "419170002"),
            ("http://snomed.info/sct", "419472004"),
            ("http://snomed.info/sct", "394539006"),
            ("http://snomed.info/sct", "420112009"),
            ("http://snomed.info/sct", "409968004"),
            ("http://snomed.info/sct", "394587001"),
            ("http://snomed.info/sct", "394913002"),
            ("http://snomed.info/sct", "408440000"),
            ("http://snomed.info/sct", "418112009"),
            ("http://snomed.info/sct", "419815003"),
            ("http://snomed.info/sct", "394914008"),
            ("http://snomed.info/sct", "408455009"),
            ("http://snomed.info/sct", "394602003"),
            ("http://snomed.info/sct", "408447002"),
            ("http://snomed.info/sct", "394810000"),
            ("http://snomed.info/sct", "408450004"),
            ("http://snomed.info/sct", "408476004"),
            ("http://snomed.info/sct", "408469009"),
            ("http://snomed.info/sct", "408466002"),
            ("http://snomed.info/sct", "408471009"),
            ("http://snomed.info/sct", "408464004"),
            ("http://snomed.info/sct", "408441001"),
            ("http://snomed.info/sct", "408465003"),
            ("http://snomed.info/sct", "394605001"),
            ("http://snomed.info/sct", "394608004"),
            ("http://snomed.info/sct", "408461007"),
            ("http://snomed.info/sct", "408460008"),
            ("http://snomed.info/sct", "408460008"),
            ("http://snomed.info/sct", "394606000"),
            ("http://snomed.info/sct", "408449004"),
            ("http://snomed.info/sct", "394608004"),
            ("http://snomed.info/sct", "418018006"),
            ("http://snomed.info/sct", "394604002"),
            ("http://snomed.info/sct", "394609007"),
            ("http://snomed.info/sct", "408474001"),
            ("http://snomed.info/sct", "394610002"),
            ("http://snomed.info/sct", "394611003"),
            ("http://snomed.info/sct", "408477008"),
            ("http://snomed.info/sct", "394801008"),
            ("http://snomed.info/sct", "408463005"),
            ("http://snomed.info/sct", "419321007"),
            ("http://snomed.info/sct", "394576009"),
            ("http://snomed.info/sct", "394590007"),
            ("http://snomed.info/sct", "409967009"),
            ("http://snomed.info/sct", "408448007"),
            ("http://snomed.info/sct", "419043006"),
            ("http://snomed.info/sct", "394612005"),
            ("http://snomed.info/sct", "394733009"),
            ("http://snomed.info/sct", "394732004"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            ("http://snomed.info/sct", "394539006", Some("Pediatric surgery"), None),
            (
                "http://snomed.info/sct",
                "394576009",
                Some("Surgical-Accident & emergency"),
                None,
            ),
            ("http://snomed.info/sct", "394577000", Some("Anesthetics"), None),
            ("http://snomed.info/sct", "394578005", Some("Audiological medicine"), None),
            ("http://snomed.info/sct", "394579002", Some("Cardiology"), None),
            ("http://snomed.info/sct", "394580004", Some("Clinical genetics"), None),
            ("http://snomed.info/sct", "394581000", Some("Community medicine"), None),
            ("http://snomed.info/sct", "394582007", Some("Dermatology"), None),
            ("http://snomed.info/sct", "394583002", Some("Endocrinology"), None),
            ("http://snomed.info/sct", "394584008", Some("Gastroenterology"), None),
            (
                "http://snomed.info/sct",
                "394585009",
                Some("Obstetrics and gynecology"),
                None,
            ),
            ("http://snomed.info/sct", "394586005", Some("Gynecology"), None),
            ("http://snomed.info/sct", "394587001", Some("Psychiatry"), None),
            (
                "http://snomed.info/sct",
                "394588006",
                Some("Pediatric (Child and adolescent) psychiatry"),
                None,
            ),
            ("http://snomed.info/sct", "394589003", Some("Nephrology"), None),
            ("http://snomed.info/sct", "394590007", Some("Thoracic medicine"), None),
            ("http://snomed.info/sct", "394591006", Some("Neurology"), None),
            ("http://snomed.info/sct", "394592004", Some("Clinical oncology"), None),
            ("http://snomed.info/sct", "394593009", Some("Medical oncology"), None),
            ("http://snomed.info/sct", "394594003", Some("Ophthalmology"), None),
            ("http://snomed.info/sct", "394597005", Some("Histopathology"), None),
            ("http://snomed.info/sct", "394598000", Some("Immunopathology"), None),
            ("http://snomed.info/sct", "394599008", Some("Neuropathology"), None),
            ("http://snomed.info/sct", "394600006", Some("Clinical pharmacology"), None),
            ("http://snomed.info/sct", "394601005", Some("Clinical physiology"), None),
            ("http://snomed.info/sct", "394602003", Some("Rehabilitation"), None),
            (
                "http://snomed.info/sct",
                "394604002",
                Some("Surgery-Ear, nose and throat surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "394605001",
                Some("Surgery-Dental-Oral surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "394606000",
                Some("Surgery-Dentistry-Restorative dentistry"),
                None,
            ),
            ("http://snomed.info/sct", "394607009", Some("Pediatric dentistry"), None),
            (
                "http://snomed.info/sct",
                "394608004",
                Some("Surgery-Dental-Orthodontics"),
                None,
            ),
            ("http://snomed.info/sct", "394609007", Some("Surgery-general"), None),
            ("http://snomed.info/sct", "394610002", Some("Surgery-Neurosurgery"), None),
            (
                "http://snomed.info/sct",
                "394611003",
                Some("Surgery-Plastic surgery"),
                None,
            ),
            ("http://snomed.info/sct", "394612005", Some("Urology"), None),
            ("http://snomed.info/sct", "394649004", Some("Nuclear medicine"), None),
            (
                "http://snomed.info/sct",
                "394732004",
                Some("Surgical specialty--OTHER-NOT LISTED"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "394733009",
                Some("Medical specialty--OTHER--NOT LISTED"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "394801008",
                Some("Surgery-Trauma and orthopedics"),
                None,
            ),
            ("http://snomed.info/sct", "394802001", Some("General medicine"), None),
            ("http://snomed.info/sct", "394803006", Some("Clinical hematology"), None),
            (
                "http://snomed.info/sct",
                "394804000",
                Some("Clinical cytogenetics and molecular genetics"),
                None,
            ),
            ("http://snomed.info/sct", "394806003", Some("Palliative medicine"), None),
            ("http://snomed.info/sct", "394807007", Some("Infectious diseases"), None),
            (
                "http://snomed.info/sct",
                "394808002",
                Some("Genito-urinary medicine"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "394809005",
                Some("Clinical neuro-physiology"),
                None,
            ),
            ("http://snomed.info/sct", "394810000", Some("Rheumatology"), None),
            ("http://snomed.info/sct", "394811001", Some("Geriatric medicine"), None),
            (
                "http://snomed.info/sct",
                "394812008",
                Some("Dental medicine specialties"),
                None,
            ),
            ("http://snomed.info/sct", "394813003", Some("Medical ophthalmology"), None),
            ("http://snomed.info/sct", "394814009", Some("General practice"), None),
            ("http://snomed.info/sct", "394821009", Some("Occupational medicine"), None),
            ("http://snomed.info/sct", "394882004", Some("Pain management"), None),
            ("http://snomed.info/sct", "394913002", Some("Psychotherapy"), None),
            ("http://snomed.info/sct", "394914008", Some("Radiology"), None),
            ("http://snomed.info/sct", "394915009", Some("General pathology"), None),
            ("http://snomed.info/sct", "394916005", Some("Hematopathology"), None),
            (
                "http://snomed.info/sct",
                "408440000",
                Some("Public health medicine"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408441001",
                Some("Surgery-Dental-Endodontics"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408443003",
                Some("General medical practice"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408444009",
                Some("Dental-General dental practice"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408446006",
                Some("Gynecological oncology"),
                None,
            ),
            ("http://snomed.info/sct", "408447002", Some("Respite care"), None),
            ("http://snomed.info/sct", "408448007", Some("Tropical medicine"), None),
            (
                "http://snomed.info/sct",
                "408449004",
                Some("Surgery-Dentistry--surgical"),
                None,
            ),
            ("http://snomed.info/sct", "408450004", Some("Sleep studies"), None),
            ("http://snomed.info/sct", "408454008", Some("Clinical microbiology"), None),
            (
                "http://snomed.info/sct",
                "408455009",
                Some("Radiology-Interventional radiology"),
                None,
            ),
            ("http://snomed.info/sct", "408459003", Some("Pediatric cardiology"), None),
            (
                "http://snomed.info/sct",
                "408460008",
                Some("Surgery-Dental-Prosthetic dentistry (Prosthodontics)"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408461007",
                Some("Surgery-Dental-Periodontal surgery"),
                None,
            ),
            ("http://snomed.info/sct", "408462000", Some("Burns care"), None),
            ("http://snomed.info/sct", "408463005", Some("Surgery-Vascular"), None),
            (
                "http://snomed.info/sct",
                "408464004",
                Some("Surgery-Colorectal surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408465003",
                Some("Surgery-Dental-Oral and maxillofacial surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408466002",
                Some("Surgery-Cardiac surgery"),
                None,
            ),
            ("http://snomed.info/sct", "408467006", Some("Adult mental illness"), None),
            ("http://snomed.info/sct", "408468001", Some("Learning disability"), None),
            (
                "http://snomed.info/sct",
                "408469009",
                Some("Surgery-Breast surgery"),
                None,
            ),
            ("http://snomed.info/sct", "408470005", Some("Obstetrics"), None),
            (
                "http://snomed.info/sct",
                "408471009",
                Some("Surgery-Cardiothoracic transplantation"),
                None,
            ),
            ("http://snomed.info/sct", "408472002", Some("Hepatology"), None),
            (
                "http://snomed.info/sct",
                "408474001",
                Some("Surgery-Hepatobiliary and pancreatic surgery"),
                None,
            ),
            ("http://snomed.info/sct", "408475000", Some("Diabetic medicine"), None),
            (
                "http://snomed.info/sct",
                "408476004",
                Some("Surgery-Bone and marrow transplantation"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408477008",
                Some("Surgery-Transplantation surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "408478003",
                Some("Critical care medicine"),
                None,
            ),
            ("http://snomed.info/sct", "408480009", Some("Clinical immunology"), None),
            ("http://snomed.info/sct", "409967009", Some("Toxicology"), None),
            ("http://snomed.info/sct", "409968004", Some("Preventive medicine"), None),
            ("http://snomed.info/sct", "410001006", Some("Military medicine"), None),
            ("http://snomed.info/sct", "410005002", Some("Dive medicine"), None),
            (
                "http://snomed.info/sct",
                "416304004",
                Some("Osteopathic manipulative medicine"),
                None,
            ),
            ("http://snomed.info/sct", "418002000", Some("Pediatric oncology"), None),
            (
                "http://snomed.info/sct",
                "418018006",
                Some("Surgery-Dermatologic surgery"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "418058008",
                Some("Pediatric gastroenterology"),
                None,
            ),
            ("http://snomed.info/sct", "418112009", Some("Pulmonary medicine"), None),
            ("http://snomed.info/sct", "418535003", Some("Pediatric immunology"), None),
            ("http://snomed.info/sct", "418652005", Some("Pediatric hematology"), None),
            (
                "http://snomed.info/sct",
                "418862001",
                Some("Pediatric infectious diseases"),
                None,
            ),
            ("http://snomed.info/sct", "418960008", Some("Otolaryngology"), None),
            ("http://snomed.info/sct", "419043006", Some("Urological oncology"), None),
            ("http://snomed.info/sct", "419170002", Some("Pediatric pulmonology"), None),
            ("http://snomed.info/sct", "419192003", Some("Internal medicine"), None),
            ("http://snomed.info/sct", "419321007", Some("Surgical oncology"), None),
            ("http://snomed.info/sct", "419365004", Some("Pediatric nephrology"), None),
            (
                "http://snomed.info/sct",
                "419472004",
                Some("Pediatric rheumatology"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "419610006",
                Some("Pediatric endocrinology"),
                None,
            ),
            ("http://snomed.info/sct", "419772000", Some("Family practice"), None),
            ("http://snomed.info/sct", "419815003", Some("Radiation oncology"), None),
            (
                "http://snomed.info/sct",
                "419983000",
                Some("Pediatric ophthalmology"),
                None,
            ),
            (
                "http://snomed.info/sct",
                "420112009",
                Some("Pediatric surgery-bone marrow transplantation"),
                None,
            ),
            ("http://snomed.info/sct", "420208008", Some("Pediatric genetics"), None),
            (
                "http://snomed.info/sct",
                "421661004",
                Some("Blood banking and transfusion medicine"),
                None,
            ),
            ("http://snomed.info/sct", "422191005", Some("Ophthalmic surgery"), None),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for PracticeSettingCodeValueSet {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for PracticeSettingCodeValueSet {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for PracticeSettingCodeValueSet {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

