// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: EvidenceCertaintyRating
///Canonical URL: http://hl7.org/fhir/ValueSet/certainty-rating
///Version: 5.0.0
///Title: Evidence Certainty Rating
///Status: draft
///The assessment of quality, confidence, or certainty.
///Compose includes 16 explicit concept codes
///Includes systems:
///- http://hl7.org/fhir/certainty-rating
pub struct EvidenceCertaintyRating;
impl EvidenceCertaintyRating {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/certainty-rating";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://hl7.org/fhir/certainty-rating"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://hl7.org/fhir/certainty-rating", "high"),
            ("http://hl7.org/fhir/certainty-rating", "moderate"),
            ("http://hl7.org/fhir/certainty-rating", "low"),
            ("http://hl7.org/fhir/certainty-rating", "very-low"),
            ("http://hl7.org/fhir/certainty-rating", "no-concern"),
            ("http://hl7.org/fhir/certainty-rating", "serious-concern"),
            ("http://hl7.org/fhir/certainty-rating", "very-serious-concern"),
            ("http://hl7.org/fhir/certainty-rating", "extremely-serious-concern"),
            ("http://hl7.org/fhir/certainty-rating", "present"),
            ("http://hl7.org/fhir/certainty-rating", "absent"),
            ("http://hl7.org/fhir/certainty-rating", "no-change"),
            ("http://hl7.org/fhir/certainty-rating", "downcode1"),
            ("http://hl7.org/fhir/certainty-rating", "downcode2"),
            ("http://hl7.org/fhir/certainty-rating", "downcode3"),
            ("http://hl7.org/fhir/certainty-rating", "upcode1"),
            ("http://hl7.org/fhir/certainty-rating", "upcode2"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            (
                "http://hl7.org/fhir/certainty-rating",
                "absent",
                Some("absent"),
                Some(
                    "possible reason for increasing quality rating was checked and found to be absent.",
                ),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "downcode1",
                Some("reduce rating: -1"),
                Some("reduce quality rating by 1."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "downcode2",
                Some("reduce rating: -2"),
                Some("reduce quality rating by 2."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "downcode3",
                Some("reduce rating: -3"),
                Some("reduce quality rating by 3."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "extremely-serious-concern",
                Some("extremely serious concern"),
                Some("extremely serious concern."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "high",
                Some("High quality"),
                Some("High quality evidence."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "low",
                Some("Low quality"),
                Some("Low quality evidence."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "moderate",
                Some("Moderate quality"),
                Some("Moderate quality evidence."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "no-change",
                Some("no change to rating"),
                Some("no change to quality rating."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "no-concern",
                Some("no serious concern"),
                Some("no serious concern."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "present",
                Some("present"),
                Some(
                    "possible reason for increasing quality rating was checked and found to be present.",
                ),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "serious-concern",
                Some("serious concern"),
                Some("serious concern."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "upcode1",
                Some("increase rating: +1"),
                Some("increase quality rating by 1."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "upcode2",
                Some("increase rating: +2"),
                Some("increase quality rating by 2."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "very-low",
                Some("Very low quality"),
                Some("Very low quality evidence."),
            ),
            (
                "http://hl7.org/fhir/certainty-rating",
                "very-serious-concern",
                Some("very serious concern"),
                Some("very serious concern."),
            ),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            "http://hl7.org/fhir/certainty-rating" => {
                super::super::code_systems::certainty_rating::EvidenceCertaintyRating::try_from_code(
                        code,
                    )
                    .is_ok()
            }
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for EvidenceCertaintyRating {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for EvidenceCertaintyRating {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for EvidenceCertaintyRating {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

