// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: DocumentSectionCodes
///Canonical URL: http://hl7.org/fhir/ValueSet/doc-section-codes
///Version: 5.0.0
///Title: Document Section Codes
///Status: draft
///Document section codes (LOINC codes used in CCDA sections).
///Compose includes 57 explicit concept codes
///Includes systems:
///- http://loinc.org
pub struct DocumentSectionCodes;
impl DocumentSectionCodes {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/doc-section-codes";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://loinc.org"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://loinc.org", "10154-3"),
            ("http://loinc.org", "10157-6"),
            ("http://loinc.org", "10160-0"),
            ("http://loinc.org", "10164-2"),
            ("http://loinc.org", "10183-2"),
            ("http://loinc.org", "10184-0"),
            ("http://loinc.org", "10187-3"),
            ("http://loinc.org", "10210-3"),
            ("http://loinc.org", "10216-0"),
            ("http://loinc.org", "10218-6"),
            ("http://loinc.org", "10218-6"),
            ("http://loinc.org", "10223-6"),
            ("http://loinc.org", "10222-8"),
            ("http://loinc.org", "11329-0"),
            ("http://loinc.org", "11348-0"),
            ("http://loinc.org", "11369-6"),
            ("http://loinc.org", "57852-6"),
            ("http://loinc.org", "11493-4"),
            ("http://loinc.org", "11535-2"),
            ("http://loinc.org", "11537-8"),
            ("http://loinc.org", "18776-5"),
            ("http://loinc.org", "18841-7"),
            ("http://loinc.org", "29299-5"),
            ("http://loinc.org", "29545-1"),
            ("http://loinc.org", "29549-3"),
            ("http://loinc.org", "29554-3"),
            ("http://loinc.org", "29762-2"),
            ("http://loinc.org", "30954-2"),
            ("http://loinc.org", "42344-2"),
            ("http://loinc.org", "42346-7"),
            ("http://loinc.org", "42348-3"),
            ("http://loinc.org", "42349-1"),
            ("http://loinc.org", "46240-8"),
            ("http://loinc.org", "46241-6"),
            ("http://loinc.org", "46264-8"),
            ("http://loinc.org", "47420-5"),
            ("http://loinc.org", "47519-4"),
            ("http://loinc.org", "48765-2"),
            ("http://loinc.org", "48768-6"),
            ("http://loinc.org", "51848-0"),
            ("http://loinc.org", "55109-3"),
            ("http://loinc.org", "55122-6"),
            ("http://loinc.org", "59768-2"),
            ("http://loinc.org", "59769-0"),
            ("http://loinc.org", "59770-8"),
            ("http://loinc.org", "59771-6"),
            ("http://loinc.org", "59772-4"),
            ("http://loinc.org", "59773-2"),
            ("http://loinc.org", "59775-7"),
            ("http://loinc.org", "59776-5"),
            ("http://loinc.org", "61149-1"),
            ("http://loinc.org", "61150-9"),
            ("http://loinc.org", "61150-9"),
            ("http://loinc.org", "69730-0"),
            ("http://loinc.org", "8648-8"),
            ("http://loinc.org", "8653-8"),
            ("http://loinc.org", "8716-3"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            ("http://loinc.org", "10154-3", None, None),
            ("http://loinc.org", "10157-6", None, None),
            ("http://loinc.org", "10160-0", None, None),
            ("http://loinc.org", "10164-2", None, None),
            ("http://loinc.org", "10183-2", None, None),
            ("http://loinc.org", "10184-0", None, None),
            ("http://loinc.org", "10187-3", None, None),
            ("http://loinc.org", "10210-3", None, None),
            ("http://loinc.org", "10216-0", None, None),
            ("http://loinc.org", "10218-6", None, None),
            ("http://loinc.org", "10222-8", None, None),
            ("http://loinc.org", "10223-6", None, None),
            ("http://loinc.org", "11329-0", None, None),
            ("http://loinc.org", "11348-0", None, None),
            ("http://loinc.org", "11369-6", None, None),
            ("http://loinc.org", "11493-4", None, None),
            ("http://loinc.org", "11535-2", None, None),
            ("http://loinc.org", "11537-8", None, None),
            ("http://loinc.org", "18776-5", None, None),
            ("http://loinc.org", "18841-7", None, None),
            ("http://loinc.org", "29299-5", None, None),
            ("http://loinc.org", "29545-1", None, None),
            ("http://loinc.org", "29549-3", None, None),
            ("http://loinc.org", "29554-3", None, None),
            ("http://loinc.org", "29762-2", None, None),
            ("http://loinc.org", "30954-2", None, None),
            ("http://loinc.org", "42344-2", None, None),
            ("http://loinc.org", "42346-7", None, None),
            ("http://loinc.org", "42348-3", None, None),
            ("http://loinc.org", "42349-1", None, None),
            ("http://loinc.org", "46240-8", None, None),
            ("http://loinc.org", "46241-6", None, None),
            ("http://loinc.org", "46264-8", None, None),
            ("http://loinc.org", "47420-5", None, None),
            ("http://loinc.org", "47519-4", None, None),
            ("http://loinc.org", "48765-2", None, None),
            ("http://loinc.org", "48768-6", None, None),
            ("http://loinc.org", "51848-0", None, None),
            ("http://loinc.org", "55109-3", None, None),
            ("http://loinc.org", "55122-6", None, None),
            ("http://loinc.org", "57852-6", None, None),
            ("http://loinc.org", "59768-2", None, None),
            ("http://loinc.org", "59769-0", None, None),
            ("http://loinc.org", "59770-8", None, None),
            ("http://loinc.org", "59771-6", None, None),
            ("http://loinc.org", "59772-4", None, None),
            ("http://loinc.org", "59773-2", None, None),
            ("http://loinc.org", "59775-7", None, None),
            ("http://loinc.org", "59776-5", None, None),
            ("http://loinc.org", "61149-1", None, None),
            ("http://loinc.org", "61150-9", None, None),
            ("http://loinc.org", "69730-0", None, None),
            ("http://loinc.org", "8648-8", None, None),
            ("http://loinc.org", "8653-8", None, None),
            ("http://loinc.org", "8716-3", None, None),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for DocumentSectionCodes {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for DocumentSectionCodes {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for DocumentSectionCodes {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

