// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: MedicationRequestIntent
///Canonical URL: http://hl7.org/fhir/ValueSet/medicationrequest-intent
///Version: 5.0.0
///Title: medicationRequest Intent
///Status: draft
///MedicationRequest Intent Codes
///Compose includes 8 explicit concept codes
///Includes systems:
///- http://hl7.org/fhir/CodeSystem/medicationrequest-intent
pub struct MedicationRequestIntent;
impl MedicationRequestIntent {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/medicationrequest-intent";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub const HAS_FILTERS: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://hl7.org/fhir/CodeSystem/medicationrequest-intent"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// compose.include.filter / compose.exclude.filter rules.
    ///
    /// These are NOT evaluated locally; they are emitted for diagnostics/routing.
    pub fn filter_rules() -> &'static [(&'static str, &'static str, &'static str)] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Return the implied system if this ValueSet constrains codes to exactly one system.
    ///
    /// This is used to allow limited validation of primitive `code` bindings.
    pub fn single_system() -> Option<&'static str> {
        let systems = Self::include_systems();
        if systems.len() == 1 {
            return Some(systems[0]);
        }
        let whole = Self::include_whole_systems();
        if whole.len() == 1 {
            return Some(whole[0]);
        }
        None
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    /// Returns true if this ValueSet is a "pure whole-system" include.
    ///
    /// Pure whole-system means membership is equivalent to validating the code exists in the
    /// included CodeSystem (no explicit include/exclude concepts, no expansion, no include.valueSet,
    /// and no filter rules).
    ///
    /// This enables routing remote checks to `CodeSystem/$validate-code` for Snowstorm and efficiency.
    pub fn is_pure_whole_system() -> bool {
        if Self::include_whole_systems().len() != 1 {
            return false;
        }
        if !Self::filter_rules().is_empty() {
            return false;
        }
        if !Self::include_value_sets().is_empty() {
            return false;
        }
        if !Self::include_pairs().is_empty() {
            return false;
        }
        if !Self::expansion_pairs().is_empty() {
            return false;
        }
        if !Self::exclude_pairs().is_empty() {
            return false;
        }
        true
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "proposal"),
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "plan"),
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "order"),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "original-order",
            ),
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "reflex-order"),
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "filler-order"),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "instance-order",
            ),
            ("http://hl7.org/fhir/CodeSystem/medicationrequest-intent", "option"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "filler-order",
                Some("Filler Order"),
                Some(
                    "The request represents the view of an authorization instantiated by a fulfilling system representing the details of the fulfiller's intention to act upon a submitted order.",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "instance-order",
                Some("Instance Order"),
                Some(
                    "The request represents an instance for the particular order and is used to generate a schedule of requests on a medication administration record (MAR).",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "option",
                Some("Option"),
                Some(
                    "The request represents a component or option for a RequestOrchestration that establishes timing, conditionality and/or  other constraints among a set of requests.",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "order",
                Some("Order"),
                Some(
                    "The request represents a request/demand and authorization for action",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "original-order",
                Some("Original Order"),
                Some(
                    "The request represents the original authorization for the medication request.",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "plan",
                Some("Plan"),
                Some(
                    "The request represents an intention to ensure something occurs without providing an authorization for others to act.",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "proposal",
                Some("Proposal"),
                Some(
                    "The request is a suggestion made by someone/something that doesn't have an intention to ensure it occurs and without providing an authorization to act",
                ),
            ),
            (
                "http://hl7.org/fhir/CodeSystem/medicationrequest-intent",
                "reflex-order",
                Some("Reflex Order"),
                Some(
                    "The request represents an automatically generated supplemental authorization for action based on a parent authorization together with initial results of the action taken against that parent authorization..",
                ),
            ),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            "http://hl7.org/fhir/CodeSystem/medicationrequest-intent" => {
                super::super::code_systems::medicationrequest_intent::MedicationRequestIntentCodes::try_from_code(
                        code,
                    )
                    .is_ok()
            }
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for MedicationRequestIntent {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for MedicationRequestIntent {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for MedicationRequestIntent {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}

