// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: OperationOutcomeCodes
///Canonical URL: http://hl7.org/fhir/ValueSet/operation-outcome
///Version: 5.0.0
///Title: Operation Outcome Codes
///Status: draft
///Operation Outcome codes for translatable phrases used by FHIR test servers (see Implementation file translations.xml)
///Compose includes 51 explicit concept codes
///Includes systems:
///- http://hl7.org/fhir/operation-outcome
pub struct OperationOutcomeCodes;
impl OperationOutcomeCodes {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/operation-outcome";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://hl7.org/fhir/operation-outcome"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://hl7.org/fhir/operation-outcome", "DELETE_MULTIPLE_MATCHES"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_AUTH_REQUIRED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_BAD_FORMAT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_BAD_SYNTAX"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_CANT_PARSE_CONTENT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_CANT_PARSE_ROOT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_CREATED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_DATE_FORMAT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_DELETED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_DELETED_DONE"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_DELETED_ID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_DUPLICATE_ID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_ERROR_PARSING"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_ID_INVALID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_ID_TOO_LONG"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_INVALID_ID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_JSON_OBJECT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_LOCAL_FAIL"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_NO_EXIST"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_NO_MATCH"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_NO_MODULE"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_NO_SUMMARY"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_OP_NOT_ALLOWED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_PARAM_CHAINED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_PARAM_INVALID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_PARAM_MODIFIER_INVALID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_PARAM_NO_REPEAT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_PARAM_UNKNOWN"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_REMOTE_FAIL"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_EXAMPLE_PROTECTED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_ID_FAIL"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_ID_MISMATCH"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_ID_MISSING"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_NOT_ALLOWED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_REQUIRED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_RESOURCE_TYPE_MISMATCH"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_SORT_UNKNOWN"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_TRANSACTION_DUPLICATE_ID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_TRANSACTION_MISSING_ID"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_UNHANDLED_NODE_TYPE"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_UNKNOWN_CONTENT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_UNKNOWN_OPERATION"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_UNKNOWN_TYPE"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_UPDATED"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_VERSION_AWARE"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_VERSION_AWARE_CONFLICT"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_VERSION_AWARE_URL"),
            ("http://hl7.org/fhir/operation-outcome", "MSG_WRONG_NS"),
            ("http://hl7.org/fhir/operation-outcome", "SEARCH_MULTIPLE"),
            ("http://hl7.org/fhir/operation-outcome", "SEARCH_NONE"),
            ("http://hl7.org/fhir/operation-outcome", "UPDATE_MULTIPLE_MATCHES"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            (
                "http://hl7.org/fhir/operation-outcome",
                "DELETE_MULTIPLE_MATCHES",
                Some("Error: Multiple matches exist for the conditional delete"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_AUTH_REQUIRED",
                Some("You must authenticate before you can use this service"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_BAD_FORMAT",
                Some("Bad Syntax: \"%s\" must be a %s'"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_BAD_SYNTAX",
                Some("Bad Syntax in %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_CANT_PARSE_CONTENT",
                Some("Unable to parse feed (entry content type = \"%s\")"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_CANT_PARSE_ROOT",
                Some("Unable to parse feed (root element name = \"%s\")"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_CREATED",
                Some("New resource created"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_DATE_FORMAT",
                Some(
                    "The Date value %s is not in the correct format (Xml Date Format required)",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_DELETED",
                Some("This resource has been deleted"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_DELETED_DONE",
                Some("Resource deleted"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_DELETED_ID",
                Some("The resource \"%s\" has been deleted"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_DUPLICATE_ID",
                Some("Duplicate Id %s for resource type %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_ERROR_PARSING",
                Some("Error parsing resource Xml (%s)"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_ID_INVALID",
                Some("Id \"%s\" has an invalid character \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_ID_TOO_LONG",
                Some("Id \"%s\" too long (length limit 36)"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_INVALID_ID",
                Some("Id not accepted"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_JSON_OBJECT",
                Some("Json Source for a resource should start with an object"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_LOCAL_FAIL",
                Some("Unable to resolve local reference to resource %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_NO_EXIST",
                Some("Resource Id \"%s\" does not exist"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_NO_MATCH",
                Some("No Resource found matching the query \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_NO_MODULE",
                Some("No module could be found to handle the request \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_NO_SUMMARY",
                Some("No Summary for this resource"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_OP_NOT_ALLOWED",
                Some(
                    "Operation %s not allowed for resource %s (due to local configuration)",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_PARAM_CHAINED",
                Some("Unknown chained parameter name \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_PARAM_INVALID",
                Some("Parameter \"%s\" content is invalid"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_PARAM_MODIFIER_INVALID",
                Some("Parameter \"%s\" modifier is invalid"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_PARAM_NO_REPEAT",
                Some("Parameter \"%s\" is not allowed to repeat"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_PARAM_UNKNOWN",
                Some("Parameter \"%s\" not understood"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_REMOTE_FAIL",
                Some("Unable to resolve local reference to resource %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_EXAMPLE_PROTECTED",
                Some(
                    "Resources with identity \"example\" cannot be deleted (for testing/training purposes)",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_ID_FAIL",
                Some("unable to allocate resource id"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_ID_MISMATCH",
                Some("Resource Id Mismatch"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_ID_MISSING",
                Some("Resource Id Missing"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_NOT_ALLOWED",
                Some("Not allowed to submit a resource for this operation"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_REQUIRED",
                Some("A resource is required"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_RESOURCE_TYPE_MISMATCH",
                Some("Resource Type Mismatch"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_SORT_UNKNOWN",
                Some("Unknown sort parameter name \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_TRANSACTION_DUPLICATE_ID",
                Some("Duplicate Identifier in transaction: %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_TRANSACTION_MISSING_ID",
                Some("Missing Identifier in transaction - an entry.id must be provided"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_UNHANDLED_NODE_TYPE",
                Some("Unhandled xml node type \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_UNKNOWN_CONTENT",
                Some("Unknown Content (%s) at %s"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_UNKNOWN_OPERATION",
                Some("unknown FHIR http operation"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_UNKNOWN_TYPE",
                Some("Resource Type \"%s\" not recognised"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_UPDATED",
                Some("existing resource updated"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_VERSION_AWARE",
                Some("Version aware updates are required for this resource"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_VERSION_AWARE_CONFLICT",
                Some(
                    "Update Conflict (server current version = \"%s\", client version referenced = \"%s\")",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_VERSION_AWARE_URL",
                Some("Version specific URL not recognised"),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "MSG_WRONG_NS",
                Some(
                    "This does not appear to be a FHIR element or resource (wrong namespace \"%s\")",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "SEARCH_MULTIPLE",
                Some("Error: Multiple matches exist for %s search parameters \"%s\""),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "SEARCH_NONE",
                Some(
                    "Error: no processable search found for %s search parameters \"%s\"",
                ),
                None,
            ),
            (
                "http://hl7.org/fhir/operation-outcome",
                "UPDATE_MULTIPLE_MATCHES",
                Some("Error: Multiple matches exist for the conditional update"),
                None,
            ),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            "http://hl7.org/fhir/operation-outcome" => {
                super::super::code_systems::operation_outcome::OperationOutcomeCodes::try_from_code(
                        code,
                    )
                    .is_ok()
            }
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for OperationOutcomeCodes {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for OperationOutcomeCodes {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept>
for OperationOutcomeCodes {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

