// @generated by AtriusValueSetGenerator
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use super::super::super::{Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR ValueSet: TargetSpecies
///Canonical URL: http://hl7.org/fhir/ValueSet/target-species
///Version: 5.0.0
///Title: Target Species
///Status: draft
///A species for which a medicinal product is intended.
///Compose includes 200 explicit concept codes
///Includes systems:
///- http://hl7.org/fhir/target-species
pub struct TargetSpecies;
impl TargetSpecies {
    pub const URL: &'static str = "http://hl7.org/fhir/ValueSet/target-species";
    pub const HAS_NONLOCAL_RULES: bool = false;
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    pub fn include_systems() -> &'static [&'static str] {
        &["http://hl7.org/fhir/target-species"]
    }
    pub fn include_value_sets() -> &'static [&'static str] {
        &[]
    }
    /// Systems that are included as whole CodeSystems but are not locally enumerable.
    ///
    /// If this is non-empty, callers should use a terminology server for definitive validation.
    pub fn include_whole_systems() -> &'static [&'static str] {
        &[]
    }
    /// Returns true only when this ValueSet can be treated as fully locally checkable.
    ///
    /// If `HAS_NONLOCAL_RULES` is true (filters, include.valueSet, or non-enumerated whole-system includes),
    /// local checks are best-effort and may require a terminology server.
    pub fn is_locally_enumerated() -> bool {
        !Self::HAS_NONLOCAL_RULES
            && (!Self::expansion_pairs().is_empty() || !Self::include_pairs().is_empty())
    }
    fn include_pairs() -> &'static [(&'static str, &'static str)] {
        &[
            ("http://hl7.org/fhir/target-species", "100000108874"),
            ("http://hl7.org/fhir/target-species", "100000108875"),
            ("http://hl7.org/fhir/target-species", "100000108876"),
            ("http://hl7.org/fhir/target-species", "100000108877"),
            ("http://hl7.org/fhir/target-species", "100000108878"),
            ("http://hl7.org/fhir/target-species", "100000108879"),
            ("http://hl7.org/fhir/target-species", "100000108880"),
            ("http://hl7.org/fhir/target-species", "100000108881"),
            ("http://hl7.org/fhir/target-species", "100000108882"),
            ("http://hl7.org/fhir/target-species", "100000108883"),
            ("http://hl7.org/fhir/target-species", "100000108884"),
            ("http://hl7.org/fhir/target-species", "100000108885"),
            ("http://hl7.org/fhir/target-species", "100000108886"),
            ("http://hl7.org/fhir/target-species", "100000108887"),
            ("http://hl7.org/fhir/target-species", "100000108888"),
            ("http://hl7.org/fhir/target-species", "100000108889"),
            ("http://hl7.org/fhir/target-species", "100000108890"),
            ("http://hl7.org/fhir/target-species", "100000108891"),
            ("http://hl7.org/fhir/target-species", "100000108892"),
            ("http://hl7.org/fhir/target-species", "100000108893"),
            ("http://hl7.org/fhir/target-species", "100000108894"),
            ("http://hl7.org/fhir/target-species", "100000108895"),
            ("http://hl7.org/fhir/target-species", "100000108896"),
            ("http://hl7.org/fhir/target-species", "100000108897"),
            ("http://hl7.org/fhir/target-species", "100000108898"),
            ("http://hl7.org/fhir/target-species", "100000108899"),
            ("http://hl7.org/fhir/target-species", "100000108900"),
            ("http://hl7.org/fhir/target-species", "100000108901"),
            ("http://hl7.org/fhir/target-species", "100000108902"),
            ("http://hl7.org/fhir/target-species", "100000108903"),
            ("http://hl7.org/fhir/target-species", "100000108904"),
            ("http://hl7.org/fhir/target-species", "100000108905"),
            ("http://hl7.org/fhir/target-species", "100000108906"),
            ("http://hl7.org/fhir/target-species", "100000108907"),
            ("http://hl7.org/fhir/target-species", "100000108908"),
            ("http://hl7.org/fhir/target-species", "100000108909"),
            ("http://hl7.org/fhir/target-species", "100000108910"),
            ("http://hl7.org/fhir/target-species", "100000108911"),
            ("http://hl7.org/fhir/target-species", "100000108912"),
            ("http://hl7.org/fhir/target-species", "100000108913"),
            ("http://hl7.org/fhir/target-species", "100000108914"),
            ("http://hl7.org/fhir/target-species", "100000108915"),
            ("http://hl7.org/fhir/target-species", "100000108916"),
            ("http://hl7.org/fhir/target-species", "100000108917"),
            ("http://hl7.org/fhir/target-species", "100000108918"),
            ("http://hl7.org/fhir/target-species", "100000108919"),
            ("http://hl7.org/fhir/target-species", "100000108920"),
            ("http://hl7.org/fhir/target-species", "100000108921"),
            ("http://hl7.org/fhir/target-species", "100000108922"),
            ("http://hl7.org/fhir/target-species", "100000108923"),
            ("http://hl7.org/fhir/target-species", "100000108924"),
            ("http://hl7.org/fhir/target-species", "100000108925"),
            ("http://hl7.org/fhir/target-species", "100000108926"),
            ("http://hl7.org/fhir/target-species", "100000108927"),
            ("http://hl7.org/fhir/target-species", "100000108928"),
            ("http://hl7.org/fhir/target-species", "100000108929"),
            ("http://hl7.org/fhir/target-species", "100000108930"),
            ("http://hl7.org/fhir/target-species", "100000108931"),
            ("http://hl7.org/fhir/target-species", "100000108932"),
            ("http://hl7.org/fhir/target-species", "100000108933"),
            ("http://hl7.org/fhir/target-species", "100000108934"),
            ("http://hl7.org/fhir/target-species", "100000108935"),
            ("http://hl7.org/fhir/target-species", "100000108936"),
            ("http://hl7.org/fhir/target-species", "100000108937"),
            ("http://hl7.org/fhir/target-species", "100000108938"),
            ("http://hl7.org/fhir/target-species", "100000108939"),
            ("http://hl7.org/fhir/target-species", "100000108940"),
            ("http://hl7.org/fhir/target-species", "100000108941"),
            ("http://hl7.org/fhir/target-species", "100000108942"),
            ("http://hl7.org/fhir/target-species", "100000108943"),
            ("http://hl7.org/fhir/target-species", "100000108944"),
            ("http://hl7.org/fhir/target-species", "100000108945"),
            ("http://hl7.org/fhir/target-species", "100000108946"),
            ("http://hl7.org/fhir/target-species", "100000108947"),
            ("http://hl7.org/fhir/target-species", "100000108948"),
            ("http://hl7.org/fhir/target-species", "100000108949"),
            ("http://hl7.org/fhir/target-species", "100000108950"),
            ("http://hl7.org/fhir/target-species", "100000108951"),
            ("http://hl7.org/fhir/target-species", "100000108952"),
            ("http://hl7.org/fhir/target-species", "100000108953"),
            ("http://hl7.org/fhir/target-species", "100000108954"),
            ("http://hl7.org/fhir/target-species", "100000108955"),
            ("http://hl7.org/fhir/target-species", "100000108956"),
            ("http://hl7.org/fhir/target-species", "100000108957"),
            ("http://hl7.org/fhir/target-species", "100000108958"),
            ("http://hl7.org/fhir/target-species", "100000108959"),
            ("http://hl7.org/fhir/target-species", "100000108960"),
            ("http://hl7.org/fhir/target-species", "100000108961"),
            ("http://hl7.org/fhir/target-species", "100000108962"),
            ("http://hl7.org/fhir/target-species", "100000108963"),
            ("http://hl7.org/fhir/target-species", "100000108964"),
            ("http://hl7.org/fhir/target-species", "100000108965"),
            ("http://hl7.org/fhir/target-species", "100000108966"),
            ("http://hl7.org/fhir/target-species", "100000108967"),
            ("http://hl7.org/fhir/target-species", "100000108968"),
            ("http://hl7.org/fhir/target-species", "100000108969"),
            ("http://hl7.org/fhir/target-species", "100000108970"),
            ("http://hl7.org/fhir/target-species", "100000108971"),
            ("http://hl7.org/fhir/target-species", "100000108972"),
            ("http://hl7.org/fhir/target-species", "100000108973"),
            ("http://hl7.org/fhir/target-species", "100000108974"),
            ("http://hl7.org/fhir/target-species", "100000108975"),
            ("http://hl7.org/fhir/target-species", "100000108976"),
            ("http://hl7.org/fhir/target-species", "100000108977"),
            ("http://hl7.org/fhir/target-species", "100000108978"),
            ("http://hl7.org/fhir/target-species", "100000108979"),
            ("http://hl7.org/fhir/target-species", "100000108980"),
            ("http://hl7.org/fhir/target-species", "100000108981"),
            ("http://hl7.org/fhir/target-species", "100000108982"),
            ("http://hl7.org/fhir/target-species", "100000108983"),
            ("http://hl7.org/fhir/target-species", "100000108984"),
            ("http://hl7.org/fhir/target-species", "100000108985"),
            ("http://hl7.org/fhir/target-species", "100000108986"),
            ("http://hl7.org/fhir/target-species", "100000108987"),
            ("http://hl7.org/fhir/target-species", "100000108988"),
            ("http://hl7.org/fhir/target-species", "100000108989"),
            ("http://hl7.org/fhir/target-species", "100000108990"),
            ("http://hl7.org/fhir/target-species", "100000108991"),
            ("http://hl7.org/fhir/target-species", "100000108992"),
            ("http://hl7.org/fhir/target-species", "100000108993"),
            ("http://hl7.org/fhir/target-species", "100000108994"),
            ("http://hl7.org/fhir/target-species", "100000108995"),
            ("http://hl7.org/fhir/target-species", "100000108996"),
            ("http://hl7.org/fhir/target-species", "100000108997"),
            ("http://hl7.org/fhir/target-species", "100000108998"),
            ("http://hl7.org/fhir/target-species", "100000108999"),
            ("http://hl7.org/fhir/target-species", "100000109000"),
            ("http://hl7.org/fhir/target-species", "100000109001"),
            ("http://hl7.org/fhir/target-species", "100000109002"),
            ("http://hl7.org/fhir/target-species", "100000109003"),
            ("http://hl7.org/fhir/target-species", "100000109004"),
            ("http://hl7.org/fhir/target-species", "100000109005"),
            ("http://hl7.org/fhir/target-species", "100000109006"),
            ("http://hl7.org/fhir/target-species", "100000109007"),
            ("http://hl7.org/fhir/target-species", "100000109008"),
            ("http://hl7.org/fhir/target-species", "100000109009"),
            ("http://hl7.org/fhir/target-species", "100000109010"),
            ("http://hl7.org/fhir/target-species", "100000109011"),
            ("http://hl7.org/fhir/target-species", "100000109012"),
            ("http://hl7.org/fhir/target-species", "100000109013"),
            ("http://hl7.org/fhir/target-species", "100000109014"),
            ("http://hl7.org/fhir/target-species", "100000109015"),
            ("http://hl7.org/fhir/target-species", "100000109016"),
            ("http://hl7.org/fhir/target-species", "100000109017"),
            ("http://hl7.org/fhir/target-species", "100000109018"),
            ("http://hl7.org/fhir/target-species", "100000109019"),
            ("http://hl7.org/fhir/target-species", "100000109020"),
            ("http://hl7.org/fhir/target-species", "100000109021"),
            ("http://hl7.org/fhir/target-species", "100000109022"),
            ("http://hl7.org/fhir/target-species", "100000109023"),
            ("http://hl7.org/fhir/target-species", "100000109024"),
            ("http://hl7.org/fhir/target-species", "100000109025"),
            ("http://hl7.org/fhir/target-species", "100000109026"),
            ("http://hl7.org/fhir/target-species", "100000109027"),
            ("http://hl7.org/fhir/target-species", "100000109028"),
            ("http://hl7.org/fhir/target-species", "100000109029"),
            ("http://hl7.org/fhir/target-species", "100000109030"),
            ("http://hl7.org/fhir/target-species", "100000109031"),
            ("http://hl7.org/fhir/target-species", "100000109032"),
            ("http://hl7.org/fhir/target-species", "100000109033"),
            ("http://hl7.org/fhir/target-species", "100000109034"),
            ("http://hl7.org/fhir/target-species", "100000109035"),
            ("http://hl7.org/fhir/target-species", "100000109036"),
            ("http://hl7.org/fhir/target-species", "100000109037"),
            ("http://hl7.org/fhir/target-species", "100000109038"),
            ("http://hl7.org/fhir/target-species", "100000109039"),
            ("http://hl7.org/fhir/target-species", "100000109040"),
            ("http://hl7.org/fhir/target-species", "100000109041"),
            ("http://hl7.org/fhir/target-species", "100000109042"),
            ("http://hl7.org/fhir/target-species", "100000109043"),
            ("http://hl7.org/fhir/target-species", "100000109044"),
            ("http://hl7.org/fhir/target-species", "100000109045"),
            ("http://hl7.org/fhir/target-species", "100000109046"),
            ("http://hl7.org/fhir/target-species", "100000109047"),
            ("http://hl7.org/fhir/target-species", "100000109048"),
            ("http://hl7.org/fhir/target-species", "100000109049"),
            ("http://hl7.org/fhir/target-species", "100000109050"),
            ("http://hl7.org/fhir/target-species", "100000109051"),
            ("http://hl7.org/fhir/target-species", "100000109052"),
            ("http://hl7.org/fhir/target-species", "100000109053"),
            ("http://hl7.org/fhir/target-species", "100000109054"),
            ("http://hl7.org/fhir/target-species", "100000109055"),
            ("http://hl7.org/fhir/target-species", "100000109056"),
            ("http://hl7.org/fhir/target-species", "100000109057"),
            ("http://hl7.org/fhir/target-species", "100000109058"),
            ("http://hl7.org/fhir/target-species", "100000109059"),
            ("http://hl7.org/fhir/target-species", "100000109060"),
            ("http://hl7.org/fhir/target-species", "100000109061"),
            ("http://hl7.org/fhir/target-species", "100000109062"),
            ("http://hl7.org/fhir/target-species", "100000109063"),
            ("http://hl7.org/fhir/target-species", "100000109064"),
            ("http://hl7.org/fhir/target-species", "100000109065"),
            ("http://hl7.org/fhir/target-species", "100000109066"),
            ("http://hl7.org/fhir/target-species", "100000109067"),
            ("http://hl7.org/fhir/target-species", "100000109068"),
            ("http://hl7.org/fhir/target-species", "100000109069"),
            ("http://hl7.org/fhir/target-species", "100000109070"),
            ("http://hl7.org/fhir/target-species", "100000109071"),
            ("http://hl7.org/fhir/target-species", "100000109072"),
            ("http://hl7.org/fhir/target-species", "100000109073"),
        ]
    }
    fn include_entries() -> &'static [(
        &'static str,
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
    )] {
        &[
            ("http://hl7.org/fhir/target-species", "100000108874", Some("Dove"), None),
            ("http://hl7.org/fhir/target-species", "100000108875", Some("Quail"), None),
            ("http://hl7.org/fhir/target-species", "100000108876", Some("Snipe"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108877",
                Some("Sparrow"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108878",
                Some("Starling"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108879", Some("Swan"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108880",
                Some("Turkey hen"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108881",
                Some("Turkey cock"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108882",
                Some("Turkeys"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108883",
                Some("Turkey for reproduction"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108884", Some("Poult"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108885",
                Some("Turtle dove"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108886", Some("Bison"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108887",
                Some("Buffalo"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108888", Some("Cows"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108889",
                Some("Cow for reproduction"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108890",
                Some("Bull for reproduction"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108891", Some("Ox"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108892",
                Some("Bullock"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108893", Some("Cattle"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108894",
                Some("Beef cattle"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108895",
                Some("Dairy cattle"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108896",
                Some("Dry cow"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108897", Some("Bull"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108898",
                Some("Lactating cow"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108899",
                Some("All other food producing species"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108900",
                Some("All non-food producing species"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108901",
                Some("All species \u{a0}"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108902",
                Some("Carnivores"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108903",
                Some("Domestic animals"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108904",
                Some("Fur animals"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108905",
                Some("Game animals"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108906",
                Some("Laboratory animals"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108907",
                Some("Major species"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108908",
                Some("Minor species"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108909",
                Some("Ruminant"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108910",
                Some("Ruminant and porcine"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108911",
                Some("Small animals"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108912",
                Some("Crocodile"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108913", Some("Frog"), None),
            ("http://hl7.org/fhir/target-species", "100000108914", Some("Iguana"), None),
            ("http://hl7.org/fhir/target-species", "100000108915", Some("Lizard"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108916",
                Some("Amphibians"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108917",
                Some("Reptiles"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108918",
                Some("Reptiles for production"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108919", Some("Snake"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108920",
                Some("Tortoise"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108921", Some("Turtle"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108922",
                Some("Honey bees"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108923",
                Some("Crustacean"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108924", Some("Spider"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108925",
                Some("Indian hen"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108926",
                Some("African Goshawk"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108927",
                Some("Black Kite"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108928",
                Some("Budgerigar"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108929",
                Some("Bustard"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108930",
                Some("Buzzard"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108931", Some("Hen"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108932",
                Some("Layer hen"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108933", Some("Cock"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108934",
                Some("Broiler"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108935",
                Some("Chickens"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108936",
                Some("Chicken embryonated eggs"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108937",
                Some("Chicken for reproduction"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108938",
                Some("Replacement chick"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108939", Some("Chick"), None),
            ("http://hl7.org/fhir/target-species", "100000108940", Some("Pullet"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108941",
                Some("Cockatiel"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108942",
                Some("Cockatoo"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108943",
                Some("Common canary"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108944", Some("Crow"), None),
            ("http://hl7.org/fhir/target-species", "100000108945", Some("Duck"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108946",
                Some("Duck broiler"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108947",
                Some("Duckling"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108948", Some("Eagle"), None),
            ("http://hl7.org/fhir/target-species", "100000108949", Some("Emu"), None),
            ("http://hl7.org/fhir/target-species", "100000108950", Some("Goose"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108951",
                Some("Guinea fowl"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108952",
                Some("Kestrel"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108953", Some("Kite"), None),
            ("http://hl7.org/fhir/target-species", "100000108954", Some("Macaw"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108955",
                Some("Ostrich"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108956", Some("Birds"), None),
            ("http://hl7.org/fhir/target-species", "100000108957", Some("Fowls"), None),
            ("http://hl7.org/fhir/target-species", "100000108958", Some("Finch"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108959",
                Some("Galliformes"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108960",
                Some("Game birds"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108961",
                Some("Pekin duck"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108962",
                Some("Ornamental birds"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108963",
                Some("Poultry"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108964", Some("Owl"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108965",
                Some("Parakeet"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108966", Some("Parrot"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108967",
                Some("Partridge"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108968",
                Some("Peregrine Falcon"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108969",
                Some("Pheasants"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108970",
                Some("Carrier pigeon"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108971",
                Some("Newborn calves"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108972",
                Some("Pregnant cow"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108973",
                Some("Pregnant heifer"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108974",
                Some("Pre-ruminant cattle"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108975",
                Some("Ruminant cattle"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108976",
                Some("Wild cattle"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108977", Some("Calf"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108978",
                Some("Heifers"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108979",
                Some("Other Bovids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108980", Some("Alpaca"), None),
            ("http://hl7.org/fhir/target-species", "100000108981", Some("Camel"), None),
            ("http://hl7.org/fhir/target-species", "100000108982", Some("Llama"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108983",
                Some("Other Camelids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108984", Some("Bitch"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108985",
                Some("Bitch for reproduction"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108986",
                Some("Adult male dog"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108987",
                Some("Adult male dog for reproduction"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108988", Some("Dogs"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108989",
                Some("Lactating bitch"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108990",
                Some("Large dog"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108991",
                Some("Medium dog"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108992",
                Some("Pregnant bitch"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108993",
                Some("Small dog"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108994",
                Some("Very large dog"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000108995",
                Some("Very small dog"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000108996", Some("Puppy"), None),
            ("http://hl7.org/fhir/target-species", "100000108997", Some("Foxes"), None),
            ("http://hl7.org/fhir/target-species", "100000108998", Some("Jackal"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000108999",
                Some("Other Canids"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109000",
                Some("Raccoon dogs"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109001", Some("Wolf"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109002",
                Some("Chamois"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109003",
                Some("Other Caprines"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109004",
                Some("Adult female goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109005",
                Some("Adult male goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109006",
                Some("Dry adult female goat"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109007", Some("Goats"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109008",
                Some("Lactating adult female goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109009",
                Some("Pregnant adult female goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109010",
                Some("Pre-ruminant goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109011",
                Some("Ruminant goat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109012",
                Some("Wild goat"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109013", Some("Kid"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109014",
                Some("Other Ovids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109015", Some("Ewe"), None),
            ("http://hl7.org/fhir/target-species", "100000109016", Some("Ram"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109017",
                Some("Dry ewe"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109018",
                Some("Lactating ewe"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109019",
                Some("Pregnant ewe"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109020",
                Some("Pre-ruminant sheep"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109021",
                Some("Ruminant sheep"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109022", Some("Sheep"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109023",
                Some("Sheep for meat production"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109024",
                Some("Dairy sheep"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109025",
                Some("Wild sheep"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109026", Some("Lamb"), None),
            ("http://hl7.org/fhir/target-species", "100000109027", Some("Elk"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109028",
                Some("Fallow deer"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109029", Some("Moose"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109030",
                Some("Antelope"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109031", Some("Cervid"), None),
            ("http://hl7.org/fhir/target-species", "100000109032", Some("Deer"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109033",
                Some("Other Deer"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109034",
                Some("Red deer"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109035",
                Some("Reindeer"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109036",
                Some("Roe deer"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109037", Some("Donkey"), None),
            ("http://hl7.org/fhir/target-species", "100000109038", Some("Mare"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109039",
                Some("Gelding"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109040", Some("Horses"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109041",
                Some("Stallion"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109042", Some("Pony"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109043",
                Some("Pregnant mare"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109044",
                Some("Non food-producing horse"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109045",
                Some("Suckling colt"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109046", Some("Colt"), None),
            ("http://hl7.org/fhir/target-species", "100000109047", Some("Mule"), None),
            ("http://hl7.org/fhir/target-species", "100000109048", Some("Equid"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109049",
                Some("Female equid"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109050",
                Some("Other Equids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109051", Some("Zebra"), None),
            ("http://hl7.org/fhir/target-species", "100000109052", Some("Bobcat"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109053",
                Some("Adult female cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109054",
                Some("Adult female cat for reproduction"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109055",
                Some("Adult male cat"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109056", Some("Cats"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109057",
                Some("Lactating cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109058",
                Some("Large cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109059",
                Some("Medium cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109060",
                Some("Pregnant cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109061",
                Some("Small cat"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109062", Some("Kitten"), None),
            ("http://hl7.org/fhir/target-species", "100000109063", Some("Cougar"), None),
            ("http://hl7.org/fhir/target-species", "100000109064", Some("Jaguar"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109065",
                Some("Leopard"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109066", Some("Lion"), None),
            ("http://hl7.org/fhir/target-species", "100000109067", Some("Lynx"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109068",
                Some("Other Felids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109069", Some("Tiger"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109070",
                Some("Tsushima wild cat"),
                None,
            ),
            (
                "http://hl7.org/fhir/target-species",
                "100000109071",
                Some("Other Leporids"),
                None,
            ),
            ("http://hl7.org/fhir/target-species", "100000109072", Some("Hare"), None),
            (
                "http://hl7.org/fhir/target-species",
                "100000109073",
                Some("Female rabbit for reproduction"),
                None,
            ),
        ]
    }
    /// Return the preferred display text for a (system, code) pair, if present in this ValueSet's explicit concepts.
    pub fn display(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, d, _def) in Self::include_entries() {
            if *s == system && *c == code {
                return *d;
            }
        }
        None
    }
    /// Return the ValueSet concept definition for a (system, code) pair, if present.
    ///
    /// In `valuesets.json` this often comes from the extension:
    /// `http://hl7.org/fhir/StructureDefinition/valueset-concept-definition`.
    pub fn definition(system: &str, code: &str) -> Option<&'static str> {
        for (s, c, _d, def) in Self::include_entries() {
            if *s == system && *c == code {
                return *def;
            }
        }
        None
    }
    /// Create a minimal `Coding` from a (system, code) pair.
    ///
    /// If this ValueSet provides an explicit display for the code, it will be populated.
    pub fn to_coding(system: &str, code: &str) -> Coding {
        let sys_uri: Uri = Element {
            id: None,
            extension: None,
            value: Some(system.to_string()),
        };
        let code_el: Code = Element {
            id: None,
            extension: None,
            value: Some(code.to_string()),
        };
        let display = Self::display(system, code)
            .map(|s| FhirString {
                id: None,
                extension: None,
                value: Some(s.to_string()),
            });
        Coding {
            id: None,
            extension: None,
            system: Some(sys_uri),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(code_el),
            display,
            user_selected: None,
        }
    }
    fn exclude_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    fn expansion_pairs() -> &'static [(&'static str, &'static str)] {
        &[]
    }
    /// Best-effort local validation for a `Coding` against this ValueSet.
    ///
    /// Rules:
    /// - Explicit excludes (compose.exclude.concept) always deny.
    /// - If expansion.contains exists, it is treated as an explicit allow-list.
    /// - Else if compose.include.concept exists, it is treated as an explicit allow-list.
    /// - Else: fall back to whole-system validation when possible (generated CodeSystem enums / RGB grammar).
    ///
    /// Note: terminology filters and include.valueSet references are NOT evaluated locally.
    pub fn contains_coding(coding: &Coding) -> bool {
        let system = match &coding.system {
            Some(s) => s.value.as_deref().unwrap_or(""),
            None => return false,
        };
        let code = match &coding.code {
            Some(c) => c.value.as_deref().unwrap_or(""),
            None => return false,
        };
        if Self::exclude_pairs().iter().any(|(s, c)| *s == system && *c == code) {
            return false;
        }
        let exp = Self::expansion_pairs();
        if !exp.is_empty() {
            return exp.iter().any(|(s, c)| *s == system && *c == code);
        }
        let inc = Self::include_pairs();
        if !inc.is_empty() {
            return inc.iter().any(|(s, c)| *s == system && *c == code);
        }
        match system {
            "http://hl7.org/fhir/target-species" => {
                super::super::code_systems::target_species::TargetSpecies::try_from_code(
                        code,
                    )
                    .is_ok()
            }
            _ => false,
        }
    }
    /// Best-effort local validation for a `CodeableConcept` against this ValueSet.
    ///
    /// Returns true if any `coding` entry is contained in the ValueSet.
    pub fn contains_codeable_concept(cc: &CodeableConcept) -> bool {
        match cc.coding.as_ref() {
            Some(codings) => codings.iter().any(|c| Self::contains_coding(c)),
            None => false,
        }
    }
    /// Convenience: validate a FHIR `code` primitive when the binding is on `code`.
    ///
    /// This only works reliably when the ValueSet includes exactly one system.
    pub fn contains_code(code: &Code) -> bool {
        let code_str = match code.value.as_deref() {
            Some(v) => v,
            None => return false,
        };
        let systems = Self::include_systems();
        if systems.len() != 1 {
            return false;
        }
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(systems[0].to_string()),
        };
        let code: Code = Element {
            id: None,
            extension: None,
            value: Some(code_str.to_string()),
        };
        let coding = Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: None,
            code: Some(code),
            display: None,
            user_selected: None,
        };
        Self::contains_coding(&coding)
    }
    /// Create a minimal `CodeableConcept` (single coding) from a (system, code) pair.
    pub fn to_codeable_concept(system: &str, code: &str) -> CodeableConcept {
        let coding = Self::to_coding(system, code);
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![coding]),
            text: None,
        }
    }
}
impl super::super::bindings::ValueSetMembership<Code> for TargetSpecies {
    fn contains(v: &Code) -> bool {
        Self::contains_code(v)
    }
}
impl super::super::bindings::ValueSetMembership<Coding> for TargetSpecies {
    fn contains(v: &Coding) -> bool {
        Self::contains_coding(v)
    }
}
impl super::super::bindings::ValueSetMembership<CodeableConcept> for TargetSpecies {
    fn contains(v: &CodeableConcept) -> bool {
        Self::contains_codeable_concept(v)
    }
}
fn is_rgb_hex(code: &str) -> bool {
    let b = code.as_bytes();
    if b.len() != 7 || b[0] != b'#' {
        return false;
    }
    fn is_hex(x: u8) -> bool {
        (b'0'..=b'9').contains(&x) || (b'a'..=b'f').contains(&x)
            || (b'A'..=b'F').contains(&x)
    }
    is_hex(b[1]) && is_hex(b[2]) && is_hex(b[3]) && is_hex(b[4]) && is_hex(b[5])
        && is_hex(b[6])
}

