// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ActionReasonCode
///Canonical URL: http://hl7.org/fhir/action-reason-code
///Version: 5.0.0
///Title: Action Reason Code
///Status: active
///Provides examples of reasons for actions to be performed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ActionReasonCode {
    ///Display: Off pathway
    ///Definition: The action should be performed because the patient was determined to be off pathway.
    #[serde(rename = "off-pathway")]
    OffPathway,
    ///Display: Risk assessment
    ///Definition: The action should be performed based on a particular risk assessment.
    #[serde(rename = "risk-assessment")]
    RiskAssessment,
    ///Display: Care gap detected
    ///Definition: The action should be performed to address a detected care gap.
    #[serde(rename = "care-gap")]
    CareGap,
    ///Display: Drug-drug interaction
    ///Definition: The action should be performed to address a detected potential drug-drug interaction.
    #[serde(rename = "drug-drug-interaction")]
    DrugDrugInteraction,
    ///Display: Quality measure
    ///Definition: The action should be performed to bring the patient's care in line with a quality measure.
    #[serde(rename = "quality-measure")]
    QualityMeasure,
}
impl ActionReasonCode {
    pub fn as_code(&self) -> &'static str {
        match self {
            ActionReasonCode::OffPathway => "off-pathway",
            ActionReasonCode::RiskAssessment => "risk-assessment",
            ActionReasonCode::CareGap => "care-gap",
            ActionReasonCode::DrugDrugInteraction => "drug-drug-interaction",
            ActionReasonCode::QualityMeasure => "quality-measure",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/action-reason-code"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ActionReasonCode {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "off-pathway" => Ok(ActionReasonCode::OffPathway),
            "risk-assessment" => Ok(ActionReasonCode::RiskAssessment),
            "care-gap" => Ok(ActionReasonCode::CareGap),
            "drug-drug-interaction" => Ok(ActionReasonCode::DrugDrugInteraction),
            "quality-measure" => Ok(ActionReasonCode::QualityMeasure),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ActionReasonCode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

