// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ActionCode
///Canonical URL: http://hl7.org/fhir/action-code
///Version: 5.0.0
///Title: Action Code
///Status: active
///Provides examples of actions to be performed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ActionCode {
    ///Display: Send a message
    ///Definition: The action indicates that a particular message should be sent to a participant in the process.
    #[serde(rename = "send-message")]
    SendMessage,
    ///Display: Collect information
    ///Definition: The action indicates that information should be collected from a participant in the process.
    #[serde(rename = "collect-information")]
    CollectInformation,
    ///Display: Prescribe a medication
    ///Definition: The action indicates that a particular medication should be prescribed to the patient.
    #[serde(rename = "prescribe-medication")]
    PrescribeMedication,
    ///Display: Recommend an immunization
    ///Definition: The action indicates that a particular immunization should be performed.
    #[serde(rename = "recommend-immunization")]
    RecommendImmunization,
    ///Display: Order a service
    ///Definition: The action indicates that a particular service should be provided.
    #[serde(rename = "order-service")]
    OrderService,
    ///Display: Propose a diagnosis
    ///Definition: The action indicates that a particular diagnosis should be proposed.
    #[serde(rename = "propose-diagnosis")]
    ProposeDiagnosis,
    ///Display: Record a detected issue
    ///Definition: The action indicates that a particular detected issue should be recorded.
    #[serde(rename = "record-detected-issue")]
    RecordDetectedIssue,
    ///Display: Record an inference
    ///Definition: The action indicates that a particular inference should be recorded.
    #[serde(rename = "record-inference")]
    RecordInference,
    ///Display: Report a flag
    ///Definition: The action indicates that a particular flag should be reported.
    #[serde(rename = "report-flag")]
    ReportFlag,
}
impl ActionCode {
    pub fn as_code(&self) -> &'static str {
        match self {
            ActionCode::SendMessage => "send-message",
            ActionCode::CollectInformation => "collect-information",
            ActionCode::PrescribeMedication => "prescribe-medication",
            ActionCode::RecommendImmunization => "recommend-immunization",
            ActionCode::OrderService => "order-service",
            ActionCode::ProposeDiagnosis => "propose-diagnosis",
            ActionCode::RecordDetectedIssue => "record-detected-issue",
            ActionCode::RecordInference => "record-inference",
            ActionCode::ReportFlag => "report-flag",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/action-code"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ActionCode {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "send-message" => Ok(ActionCode::SendMessage),
            "collect-information" => Ok(ActionCode::CollectInformation),
            "prescribe-medication" => Ok(ActionCode::PrescribeMedication),
            "recommend-immunization" => Ok(ActionCode::RecommendImmunization),
            "order-service" => Ok(ActionCode::OrderService),
            "propose-diagnosis" => Ok(ActionCode::ProposeDiagnosis),
            "record-detected-issue" => Ok(ActionCode::RecordDetectedIssue),
            "record-inference" => Ok(ActionCode::RecordInference),
            "report-flag" => Ok(ActionCode::ReportFlag),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ActionCode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

