// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: AllergyIntoleranceCategory
///Canonical URL: http://hl7.org/fhir/allergy-intolerance-category
///Version: 5.0.0
///Title: Allergy Intolerance Category
///Status: active
///Category of an identified substance associated with allergies or intolerances.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AllergyIntoleranceCategory {
    ///Display: Food
    ///Definition: Any substance consumed to provide nutritional support for the body.
    #[serde(rename = "food")]
    Food,
    ///Display: Medication
    ///Definition: Substances administered to achieve a physiological effect.
    #[serde(rename = "medication")]
    Medication,
    ///Display: Environment
    ///Definition: Any substances that are encountered in the environment, including any substance not already classified as food, medication, or biologic.
    #[serde(rename = "environment")]
    Environment,
    ///Display: Biologic
    ///Definition: A preparation that is synthesized from living organisms or their products, especially a human or animal protein, such as a hormone or antitoxin, that is used as a diagnostic, preventive, or therapeutic agent. Examples of biologic medications include: vaccines; allergenic extracts, which are used for both diagnosis and treatment (for example, allergy shots); gene therapies; cellular therapies.  There are other biologic products, such as tissues, which are not typically associated with allergies.
    #[serde(rename = "biologic")]
    Biologic,
}
impl AllergyIntoleranceCategory {
    pub fn as_code(&self) -> &'static str {
        match self {
            AllergyIntoleranceCategory::Food => "food",
            AllergyIntoleranceCategory::Medication => "medication",
            AllergyIntoleranceCategory::Environment => "environment",
            AllergyIntoleranceCategory::Biologic => "biologic",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/allergy-intolerance-category"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for AllergyIntoleranceCategory {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "food" => Ok(AllergyIntoleranceCategory::Food),
            "medication" => Ok(AllergyIntoleranceCategory::Medication),
            "environment" => Ok(AllergyIntoleranceCategory::Environment),
            "biologic" => Ok(AllergyIntoleranceCategory::Biologic),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for AllergyIntoleranceCategory {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

