// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ArtifactAssessmentWorkflowStatus
///Canonical URL: http://hl7.org/fhir/artifactassessment-workflow-status
///Version: 5.0.0
///Title: Artifact Assessment Workflow Status
///Status: active
///Possible values for the workflow status of the comment or assessment, typically used to coordinate workflow around the process of accepting and rejecting changes and comments on the artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ArtifactAssessmentWorkflowStatus {
    ///Display: Submitted
    ///Definition: The comment has been submitted, but the responsible party has not yet been determined, or the responsible party has not yet determined the next steps to be taken.
    #[serde(rename = "submitted")]
    Submitted,
    ///Display: Triaged
    ///Definition: The comment has been triaged, meaning the responsible party has been determined and next steps have been identified to address the comment.
    #[serde(rename = "triaged")]
    Triaged,
    ///Display: Waiting for Input
    ///Definition: The comment is waiting for input from a specific party before next steps can be taken.
    #[serde(rename = "waiting-for-input")]
    WaitingForInput,
    ///Display: Resolved - No Change
    ///Definition: The comment has been resolved and no changes resulted from the resolution
    #[serde(rename = "resolved-no-change")]
    ResolvedNoChange,
    ///Display: Resolved - Change Required
    ///Definition: The comment has been resolved and changes are required to address the comment
    #[serde(rename = "resolved-change-required")]
    ResolvedChangeRequired,
    ///Display: Deferred
    ///Definition: The comment is acceptable, but resolution of the comment and application of any associated changes have been deferred
    #[serde(rename = "deferred")]
    Deferred,
    ///Display: Duplicate
    ///Definition: The comment is a duplicate of another comment already received
    #[serde(rename = "duplicate")]
    Duplicate,
    ///Display: Applied
    ///Definition: The comment is resolved and any necessary changes have been applied
    #[serde(rename = "applied")]
    Applied,
    ///Display: Published
    ///Definition: The necessary changes to the artifact have been published in a new version of the artifact
    #[serde(rename = "published")]
    Published,
    ///Display: Entered in Error
    ///Definition: The assessment was entered in error
    #[serde(rename = "entered-in-error")]
    EnteredInError,
}
impl ArtifactAssessmentWorkflowStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            ArtifactAssessmentWorkflowStatus::Submitted => "submitted",
            ArtifactAssessmentWorkflowStatus::Triaged => "triaged",
            ArtifactAssessmentWorkflowStatus::WaitingForInput => "waiting-for-input",
            ArtifactAssessmentWorkflowStatus::ResolvedNoChange => "resolved-no-change",
            ArtifactAssessmentWorkflowStatus::ResolvedChangeRequired => {
                "resolved-change-required"
            }
            ArtifactAssessmentWorkflowStatus::Deferred => "deferred",
            ArtifactAssessmentWorkflowStatus::Duplicate => "duplicate",
            ArtifactAssessmentWorkflowStatus::Applied => "applied",
            ArtifactAssessmentWorkflowStatus::Published => "published",
            ArtifactAssessmentWorkflowStatus::EnteredInError => "entered-in-error",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/artifactassessment-workflow-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ArtifactAssessmentWorkflowStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "submitted" => Ok(ArtifactAssessmentWorkflowStatus::Submitted),
            "triaged" => Ok(ArtifactAssessmentWorkflowStatus::Triaged),
            "waiting-for-input" => Ok(ArtifactAssessmentWorkflowStatus::WaitingForInput),
            "resolved-no-change" => {
                Ok(ArtifactAssessmentWorkflowStatus::ResolvedNoChange)
            }
            "resolved-change-required" => {
                Ok(ArtifactAssessmentWorkflowStatus::ResolvedChangeRequired)
            }
            "deferred" => Ok(ArtifactAssessmentWorkflowStatus::Deferred),
            "duplicate" => Ok(ArtifactAssessmentWorkflowStatus::Duplicate),
            "applied" => Ok(ArtifactAssessmentWorkflowStatus::Applied),
            "published" => Ok(ArtifactAssessmentWorkflowStatus::Published),
            "entered-in-error" => Ok(ArtifactAssessmentWorkflowStatus::EnteredInError),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ArtifactAssessmentWorkflowStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

