// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: CompositionStatus
///Canonical URL: http://hl7.org/fhir/composition-status
///Version: 5.0.0
///Title: Composition Status
///Status: active
///The workflow/clinical status of the composition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CompositionStatus {
    ///Display: Registered
    ///Definition: The existence of the composition is registered, but there is nothing yet available.
    #[serde(rename = "registered")]
    Registered,
    ///Display: Partial
    ///Definition: This is a partial (e.g. initial, interim or preliminary) composition: data in the composition may be incomplete or unverified.
    #[serde(rename = "partial")]
    Partial,
    ///Display: Final
    ///Definition: This version of the composition is complete and verified by an appropriate person and no further work is planned. Any subsequent updates would be on a new version of the composition.
    #[serde(rename = "final")]
    Final,
    ///Display: Amended
    ///Definition: The composition content or the referenced resources have been modified (edited or added to) subsequent to being released as "final" and the composition is complete and verified by an authorized person.
    #[serde(rename = "amended")]
    Amended,
    ///Display: Cancelled
    ///Definition: The composition is unavailable because the measurement was not started or not completed (also sometimes called "aborted").
    #[serde(rename = "cancelled")]
    Cancelled,
    ///Display: Entered in Error
    ///Definition: The composition or document was originally created/issued in error, and this is an amendment that marks that the entire series should not be considered as valid.
    #[serde(rename = "entered-in-error")]
    EnteredInError,
    ///Display: Deprecated
    ///Definition: This composition has been withdrawn or superseded and should no longer be used.
    #[serde(rename = "deprecated")]
    Deprecated,
    ///Display: Unknown
    ///Definition: The authoring/source system does not know which of the status values currently applies for this observation. Note: This concept is not to be used for "other" - one of the listed statuses is presumed to apply, but the authoring/source system does not know which.
    #[serde(rename = "unknown")]
    Unknown,
}
impl CompositionStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            CompositionStatus::Registered => "registered",
            CompositionStatus::Partial => "partial",
            CompositionStatus::Final => "final",
            CompositionStatus::Amended => "amended",
            CompositionStatus::Cancelled => "cancelled",
            CompositionStatus::EnteredInError => "entered-in-error",
            CompositionStatus::Deprecated => "deprecated",
            CompositionStatus::Unknown => "unknown",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/composition-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for CompositionStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "registered" => Ok(CompositionStatus::Registered),
            "partial" => Ok(CompositionStatus::Partial),
            "final" => Ok(CompositionStatus::Final),
            "amended" => Ok(CompositionStatus::Amended),
            "cancelled" => Ok(CompositionStatus::Cancelled),
            "entered-in-error" => Ok(CompositionStatus::EnteredInError),
            "deprecated" => Ok(CompositionStatus::Deprecated),
            "unknown" => Ok(CompositionStatus::Unknown),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for CompositionStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

