// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: DeviceAssociation
///Canonical URL: http://hl7.org/fhir/deviceassociation-status
///Version: 5.0.0
///Title: DeviceAssociation Status Codes
///Status: active
///DeviceAssociation Status Codes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DeviceAssociation {
    ///Display: Implanted
    ///Definition: The device is implanted in the patient.
    #[serde(rename = "implanted")]
    Implanted,
    ///Display: Explanted
    ///Definition: The device is no longer implanted in the patient. Note that this is not the value to be used for devices that have never been implanted. In those cases, no value or a specific value can be used.
    #[serde(rename = "explanted")]
    Explanted,
    ///Display: Entered in Error
    ///Definition: The association was entered in error and therefore nullified.
    #[serde(rename = "entered-in-error")]
    EnteredInError,
    ///Display: Attached
    ///Definition: The device is attached to the patient but not implanted in the patient.
    #[serde(rename = "attached")]
    Attached,
    ///Display: Unknown
    ///Definition: The association status of the device has not been determined.
    #[serde(rename = "unknown")]
    Unknown,
}
impl DeviceAssociation {
    pub fn as_code(&self) -> &'static str {
        match self {
            DeviceAssociation::Implanted => "implanted",
            DeviceAssociation::Explanted => "explanted",
            DeviceAssociation::EnteredInError => "entered-in-error",
            DeviceAssociation::Attached => "attached",
            DeviceAssociation::Unknown => "unknown",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/deviceassociation-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for DeviceAssociation {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "implanted" => Ok(DeviceAssociation::Implanted),
            "explanted" => Ok(DeviceAssociation::Explanted),
            "entered-in-error" => Ok(DeviceAssociation::EnteredInError),
            "attached" => Ok(DeviceAssociation::Attached),
            "unknown" => Ok(DeviceAssociation::Unknown),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for DeviceAssociation {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

