// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: EncounterStatus
///Canonical URL: http://hl7.org/fhir/encounter-status
///Version: 5.0.0
///Title: Encounter Status
///Status: active
///Current state of the encounter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EncounterStatus {
    ///Display: Planned
    ///Definition: The Encounter has not yet started.
    #[serde(rename = "planned")]
    Planned,
    ///Display: In Progress
    ///Definition: The Encounter has begun and the patient is present / the practitioner and the patient are meeting.
    #[serde(rename = "in-progress")]
    InProgress,
    ///Display: On Hold
    ///Definition: The Encounter has begun, but is currently on hold, e.g. because the patient is temporarily on leave.
    #[serde(rename = "on-hold")]
    OnHold,
    ///Display: Discharged
    ///Definition: The Encounter has been clinically completed, the patient has been discharged from the facility or the visit has ended, and the patient may have departed (refer to subjectStatus). While the encounter is in this status, administrative activities are usually performed, collating all required documentation and charge information before being released for billing, at which point the status will move to completed.
    #[serde(rename = "discharged")]
    Discharged,
    ///Display: Completed
    ///Definition: The Encounter has ended.
    #[serde(rename = "completed")]
    Completed,
    ///Display: Cancelled
    ///Definition: The Encounter has ended before it has begun.
    #[serde(rename = "cancelled")]
    Cancelled,
    ///Display: Discontinued
    ///Definition: The Encounter has started, but was not able to be completed. Further action may need to be performed, such as rescheduling appointments related to this encounter.
    #[serde(rename = "discontinued")]
    Discontinued,
    ///Display: Entered in Error
    ///Definition: This instance should not have been part of this patient's medical record.
    #[serde(rename = "entered-in-error")]
    EnteredInError,
    ///Display: Unknown
    ///Definition: The encounter status is unknown. Note that "unknown" is a value of last resort and every attempt should be made to provide a meaningful value other than "unknown".
    #[serde(rename = "unknown")]
    Unknown,
}
impl EncounterStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            EncounterStatus::Planned => "planned",
            EncounterStatus::InProgress => "in-progress",
            EncounterStatus::OnHold => "on-hold",
            EncounterStatus::Discharged => "discharged",
            EncounterStatus::Completed => "completed",
            EncounterStatus::Cancelled => "cancelled",
            EncounterStatus::Discontinued => "discontinued",
            EncounterStatus::EnteredInError => "entered-in-error",
            EncounterStatus::Unknown => "unknown",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/encounter-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for EncounterStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "planned" => Ok(EncounterStatus::Planned),
            "in-progress" => Ok(EncounterStatus::InProgress),
            "on-hold" => Ok(EncounterStatus::OnHold),
            "discharged" => Ok(EncounterStatus::Discharged),
            "completed" => Ok(EncounterStatus::Completed),
            "cancelled" => Ok(EncounterStatus::Cancelled),
            "discontinued" => Ok(EncounterStatus::Discontinued),
            "entered-in-error" => Ok(EncounterStatus::EnteredInError),
            "unknown" => Ok(EncounterStatus::Unknown),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for EncounterStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

