// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: EncounterLocationStatus
///Canonical URL: http://hl7.org/fhir/encounter-location-status
///Version: 5.0.0
///Title: Encounter Location Status
///Status: active
///The status of the location.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EncounterLocationStatus {
    ///Display: Planned
    ///Definition: The patient is planned to be moved to this location at some point in the future.
    #[serde(rename = "planned")]
    Planned,
    ///Display: Active
    ///Definition: The patient is currently at this location, or was between the period specified.
    ///
    ///A system may update these records when the patient leaves the location to either reserved, or completed.
    #[serde(rename = "active")]
    Active,
    ///Display: Reserved
    ///Definition: This location is held empty for this patient.
    #[serde(rename = "reserved")]
    Reserved,
    ///Display: Completed
    ///Definition: The patient was at this location during the period specified.
    ///
    ///Not to be used when the patient is currently at the location.
    #[serde(rename = "completed")]
    Completed,
}
impl EncounterLocationStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            EncounterLocationStatus::Planned => "planned",
            EncounterLocationStatus::Active => "active",
            EncounterLocationStatus::Reserved => "reserved",
            EncounterLocationStatus::Completed => "completed",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/encounter-location-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for EncounterLocationStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "planned" => Ok(EncounterLocationStatus::Planned),
            "active" => Ok(EncounterLocationStatus::Active),
            "reserved" => Ok(EncounterLocationStatus::Reserved),
            "completed" => Ok(EncounterLocationStatus::Completed),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for EncounterLocationStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

