// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ReportSectionType
///Canonical URL: http://hl7.org/fhir/evidence-report-section
///Version: 5.0.0
///Title: Report Section Type
///Status: active
///Evidence Report Section Type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReportSectionType {
    ///Display: Evidence Results
    ///Definition: Evidence Results.
    #[serde(rename = "Evidence")]
    Evidence,
    ///Display: Evidence Results for the intervention exposure only
    ///Definition: Evidence Results for the intervention exposure only.
    #[serde(rename = "Intervention-group-alone-Evidence")]
    InterventionGroupAloneEvidence,
    ///Display: Evidence Results for comparison of Intervention and Control
    ///Definition: Evidence Results for comparison of Intervention and Control.
    #[serde(rename = "Intervention-vs-Control-Evidence")]
    InterventionVsControlEvidence,
    ///Display: Evidence Results for the control exposure only
    ///Definition: Evidence Results for the control exposure only.
    #[serde(rename = "Control-group-alone-Evidence")]
    ControlGroupAloneEvidence,
    ///Display: Evidence Variables used
    ///Definition: Evidence Variables used.
    #[serde(rename = "EvidenceVariable")]
    Evidencevariable,
    ///Display: Evidence Variables actually observed
    ///Definition: Evidence Variables as observed in the research data.
    #[serde(rename = "EvidenceVariable-observed")]
    EvidencevariableObserved,
    ///Display: Evidence Variables intended for interpretation
    ///Definition: Evidence Variables intended for interpretation.
    #[serde(rename = "EvidenceVariable-intended")]
    EvidencevariableIntended,
    ///Display: Evidence Variable in variable role Population
    ///Definition: Evidence Variable in variable role Population.
    #[serde(rename = "EvidenceVariable-population")]
    EvidencevariablePopulation,
    ///Display: Evidence Variable in variable role Exposure
    ///Definition: Evidence Variable in variable role Exposure.
    #[serde(rename = "EvidenceVariable-exposure")]
    EvidencevariableExposure,
    ///Display: Evidence Variable in variable role Outcome (MeasuredVariable)
    ///Definition: Evidence Variable in variable role Outcome (MeasuredVariable).
    #[serde(rename = "EvidenceVariable-outcome")]
    EvidencevariableOutcome,
    ///Display: Efficacy-outcomes
    ///Definition: Outcomes related to efficacy or potential benefits of interventions.
    #[serde(rename = "Efficacy-outcomes")]
    EfficacyOutcomes,
    ///Display: Harms outcomes
    ///Definition: Outcomes related to adverse effects or potential harms of interventions.
    #[serde(rename = "Harms-outcomes")]
    HarmsOutcomes,
    ///Display: Sample Size
    ///Definition: Sample Size.
    #[serde(rename = "SampleSize")]
    Samplesize,
    ///Display: References
    ///Definition: References.
    #[serde(rename = "References")]
    References,
    ///Display: Assertion
    ///Definition: Assertion.
    #[serde(rename = "Assertion")]
    Assertion,
    ///Display: Reasons
    ///Definition: Reasons.
    #[serde(rename = "Reasons")]
    Reasons,
    ///Display: Certainty of Evidence
    ///Definition: Certainty of Evidence.
    #[serde(rename = "Certainty-of-Evidence")]
    CertaintyOfEvidence,
    ///Display: Evidence Classifier section
    ///Definition: This section is used for classifiers of the evidence.
    #[serde(rename = "Evidence-Classifier")]
    EvidenceClassifier,
    ///Display: Warnings
    ///Definition: Warnings.
    #[serde(rename = "Warnings")]
    Warnings,
    ///Display: Text Summary
    ///Definition: Denotes a section specifying text summary for a report.
    #[serde(rename = "Text-Summary")]
    TextSummary,
    ///Display: Summary of Body of Evidence Findings
    ///Definition: Summary of Body of Evidence Findings.
    #[serde(rename = "SummaryOfBodyOfEvidenceFindings")]
    Summaryofbodyofevidencefindings,
    ///Display: Summary of Individual Study Findings
    ///Definition: Summary of Individual Study Findings.
    #[serde(rename = "SummaryOfIndividualStudyFindings")]
    Summaryofindividualstudyfindings,
    ///Display: Header
    ///Definition: Denotes the header to use for a Text Summary or above a Table.
    #[serde(rename = "Header")]
    Header,
    ///Display: Tables
    ///Definition: Tables.
    #[serde(rename = "Tables")]
    Tables,
    ///Display: Table
    #[serde(rename = "Table")]
    Table,
    ///Display: Row Headers
    ///Definition: Denotes a section specifying row headers for a tabular report.
    #[serde(rename = "Row-Headers")]
    RowHeaders,
    ///Display: Column Header
    ///Definition: Denotes the header to use for the column for a tabular report.
    #[serde(rename = "Column-Header")]
    ColumnHeader,
    ///Display: Column Headers
    ///Definition: Denotes a section specifying column headers for a tabular report.
    #[serde(rename = "Column-Headers")]
    ColumnHeaders,
}
impl ReportSectionType {
    pub fn as_code(&self) -> &'static str {
        match self {
            ReportSectionType::Evidence => "Evidence",
            ReportSectionType::InterventionGroupAloneEvidence => {
                "Intervention-group-alone-Evidence"
            }
            ReportSectionType::InterventionVsControlEvidence => {
                "Intervention-vs-Control-Evidence"
            }
            ReportSectionType::ControlGroupAloneEvidence => {
                "Control-group-alone-Evidence"
            }
            ReportSectionType::Evidencevariable => "EvidenceVariable",
            ReportSectionType::EvidencevariableObserved => "EvidenceVariable-observed",
            ReportSectionType::EvidencevariableIntended => "EvidenceVariable-intended",
            ReportSectionType::EvidencevariablePopulation => {
                "EvidenceVariable-population"
            }
            ReportSectionType::EvidencevariableExposure => "EvidenceVariable-exposure",
            ReportSectionType::EvidencevariableOutcome => "EvidenceVariable-outcome",
            ReportSectionType::EfficacyOutcomes => "Efficacy-outcomes",
            ReportSectionType::HarmsOutcomes => "Harms-outcomes",
            ReportSectionType::Samplesize => "SampleSize",
            ReportSectionType::References => "References",
            ReportSectionType::Assertion => "Assertion",
            ReportSectionType::Reasons => "Reasons",
            ReportSectionType::CertaintyOfEvidence => "Certainty-of-Evidence",
            ReportSectionType::EvidenceClassifier => "Evidence-Classifier",
            ReportSectionType::Warnings => "Warnings",
            ReportSectionType::TextSummary => "Text-Summary",
            ReportSectionType::Summaryofbodyofevidencefindings => {
                "SummaryOfBodyOfEvidenceFindings"
            }
            ReportSectionType::Summaryofindividualstudyfindings => {
                "SummaryOfIndividualStudyFindings"
            }
            ReportSectionType::Header => "Header",
            ReportSectionType::Tables => "Tables",
            ReportSectionType::Table => "Table",
            ReportSectionType::RowHeaders => "Row-Headers",
            ReportSectionType::ColumnHeader => "Column-Header",
            ReportSectionType::ColumnHeaders => "Column-Headers",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/evidence-report-section"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ReportSectionType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "Evidence" => Ok(ReportSectionType::Evidence),
            "Intervention-group-alone-Evidence" => {
                Ok(ReportSectionType::InterventionGroupAloneEvidence)
            }
            "Intervention-vs-Control-Evidence" => {
                Ok(ReportSectionType::InterventionVsControlEvidence)
            }
            "Control-group-alone-Evidence" => {
                Ok(ReportSectionType::ControlGroupAloneEvidence)
            }
            "EvidenceVariable" => Ok(ReportSectionType::Evidencevariable),
            "EvidenceVariable-observed" => {
                Ok(ReportSectionType::EvidencevariableObserved)
            }
            "EvidenceVariable-intended" => {
                Ok(ReportSectionType::EvidencevariableIntended)
            }
            "EvidenceVariable-population" => {
                Ok(ReportSectionType::EvidencevariablePopulation)
            }
            "EvidenceVariable-exposure" => {
                Ok(ReportSectionType::EvidencevariableExposure)
            }
            "EvidenceVariable-outcome" => Ok(ReportSectionType::EvidencevariableOutcome),
            "Efficacy-outcomes" => Ok(ReportSectionType::EfficacyOutcomes),
            "Harms-outcomes" => Ok(ReportSectionType::HarmsOutcomes),
            "SampleSize" => Ok(ReportSectionType::Samplesize),
            "References" => Ok(ReportSectionType::References),
            "Assertion" => Ok(ReportSectionType::Assertion),
            "Reasons" => Ok(ReportSectionType::Reasons),
            "Certainty-of-Evidence" => Ok(ReportSectionType::CertaintyOfEvidence),
            "Evidence-Classifier" => Ok(ReportSectionType::EvidenceClassifier),
            "Warnings" => Ok(ReportSectionType::Warnings),
            "Text-Summary" => Ok(ReportSectionType::TextSummary),
            "SummaryOfBodyOfEvidenceFindings" => {
                Ok(ReportSectionType::Summaryofbodyofevidencefindings)
            }
            "SummaryOfIndividualStudyFindings" => {
                Ok(ReportSectionType::Summaryofindividualstudyfindings)
            }
            "Header" => Ok(ReportSectionType::Header),
            "Tables" => Ok(ReportSectionType::Tables),
            "Table" => Ok(ReportSectionType::Table),
            "Row-Headers" => Ok(ReportSectionType::RowHeaders),
            "Column-Header" => Ok(ReportSectionType::ColumnHeader),
            "Column-Headers" => Ok(ReportSectionType::ColumnHeaders),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ReportSectionType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

