// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ImagingSelection3DGraphicType
///Canonical URL: http://hl7.org/fhir/imagingselection-3dgraphictype
///Version: 5.0.0
///Title: Imaging Selection3 D Graphic Type
///Status: active
///The type of coordinates describing an image region.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ImagingSelection3DGraphicType {
    ///Display: POINT
    ///Definition: A single location denoted by a single (x,y,z) triplet.
    #[serde(rename = "point")]
    Point,
    ///Display: MULTIPOINT
    ///Definition: multiple locations each denoted by an (x,y,z) triplet; the points need not be coplanar.
    #[serde(rename = "multipoint")]
    Multipoint,
    ///Display: POLYLINE
    ///Definition: a series of connected line segments with ordered vertices denoted by (x,y,z) triplets; the points need not be coplanar.
    #[serde(rename = "polyline")]
    Polyline,
    ///Display: POLYGON
    ///Definition: a series of connected line segments with ordered vertices denoted by (x,y,z) triplets, where the first and last vertices shall be the same forming a polygon; the points shall be coplanar.
    #[serde(rename = "polygon")]
    Polygon,
    ///Display: ELLIPSE
    ///Definition: an ellipse defined by four (x,y,z) triplets, the first two triplets specifying the endpoints of the major axis and the second two triplets specifying the endpoints of the minor axis.
    #[serde(rename = "ellipse")]
    Ellipse,
    ///Display: ELLIPSOID
    ///Definition: a three-dimensional geometric surface whose plane sections are either ellipses or circles and contains three intersecting orthogonal axes, "a", "b", and "c"; the ellipsoid is defined by six (x,y,z) triplets, the first and second triplets specifying the endpoints of axis "a", the third and fourth triplets specifying the endpoints of axis "b", and the fifth and sixth triplets specifying the endpoints of axis "c".
    #[serde(rename = "ellipsoid")]
    Ellipsoid,
}
impl ImagingSelection3DGraphicType {
    pub fn as_code(&self) -> &'static str {
        match self {
            ImagingSelection3DGraphicType::Point => "point",
            ImagingSelection3DGraphicType::Multipoint => "multipoint",
            ImagingSelection3DGraphicType::Polyline => "polyline",
            ImagingSelection3DGraphicType::Polygon => "polygon",
            ImagingSelection3DGraphicType::Ellipse => "ellipse",
            ImagingSelection3DGraphicType::Ellipsoid => "ellipsoid",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/imagingselection-3dgraphictype"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ImagingSelection3DGraphicType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "point" => Ok(ImagingSelection3DGraphicType::Point),
            "multipoint" => Ok(ImagingSelection3DGraphicType::Multipoint),
            "polyline" => Ok(ImagingSelection3DGraphicType::Polyline),
            "polygon" => Ok(ImagingSelection3DGraphicType::Polygon),
            "ellipse" => Ok(ImagingSelection3DGraphicType::Ellipse),
            "ellipsoid" => Ok(ImagingSelection3DGraphicType::Ellipsoid),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ImagingSelection3DGraphicType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

