// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: InventoryReportStatus
///Canonical URL: http://hl7.org/fhir/inventoryreport-status
///Version: 5.0.0
///Title: Inventory Report Status
///Status: active
///The status of the InventoryReport.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InventoryReportStatus {
    ///Display: Draft
    ///Definition: The existence of the report is registered, but it is still without content or only some preliminary content.
    #[serde(rename = "draft")]
    Draft,
    ///Display: Requested
    ///Definition: The inventory report has been requested but there is no data available.
    #[serde(rename = "requested")]
    Requested,
    ///Display: Active
    ///Definition: This report is submitted as current.
    #[serde(rename = "active")]
    Active,
    ///Display: Entered in Error
    ///Definition: The report has been withdrawn following a previous final release.  This electronic record should never have existed, though it is possible that real-world decisions were based on it.
    #[serde(rename = "entered-in-error")]
    EnteredInError,
}
impl InventoryReportStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            InventoryReportStatus::Draft => "draft",
            InventoryReportStatus::Requested => "requested",
            InventoryReportStatus::Active => "active",
            InventoryReportStatus::EnteredInError => "entered-in-error",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/inventoryreport-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for InventoryReportStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "draft" => Ok(InventoryReportStatus::Draft),
            "requested" => Ok(InventoryReportStatus::Requested),
            "active" => Ok(InventoryReportStatus::Active),
            "entered-in-error" => Ok(InventoryReportStatus::EnteredInError),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for InventoryReportStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

