// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: InventoryItemNameType
///Canonical URL: http://hl7.org/fhir/inventoryitem-nametype
///Version: 5.0.0
///Title: InventoryItem Name Type
///Status: active
///InventoryItem Name Type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InventoryItemNameType {
    ///Display: Trade Name
    ///Definition: The official trade name of the item.
    #[serde(rename = "trade-name")]
    TradeName,
    ///Display: Alias
    ///Definition: An alias or common name for the item.
    #[serde(rename = "alias")]
    Alias,
    ///Display: Original Name
    ///Definition: The original name of the item.
    #[serde(rename = "original-name")]
    OriginalName,
    ///Display: Preferred
    ///Definition: The preferred name of the item.
    #[serde(rename = "preferred")]
    Preferred,
}
impl InventoryItemNameType {
    pub fn as_code(&self) -> &'static str {
        match self {
            InventoryItemNameType::TradeName => "trade-name",
            InventoryItemNameType::Alias => "alias",
            InventoryItemNameType::OriginalName => "original-name",
            InventoryItemNameType::Preferred => "preferred",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/inventoryitem-nametype"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for InventoryItemNameType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "trade-name" => Ok(InventoryItemNameType::TradeName),
            "alias" => Ok(InventoryItemNameType::Alias),
            "original-name" => Ok(InventoryItemNameType::OriginalName),
            "preferred" => Ok(InventoryItemNameType::Preferred),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for InventoryItemNameType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

