// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: MedicinalProductPackageType
///Canonical URL: http://hl7.org/fhir/medicinal-product-package-type
///Version: 5.0.0
///Title: Medicinal Product Package Type
///Status: active
///Types of medicinal product packs
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MedicinalProductPackageType {
    ///Display: Ampoule
    #[serde(rename = "100000073490")]
    N100000073490,
    ///Display: Applicator
    #[serde(rename = "100000073491")]
    N100000073491,
    ///Display: Automatic injection device
    #[serde(rename = "100000073492")]
    N100000073492,
    ///Display: Bag
    #[serde(rename = "100000073493")]
    N100000073493,
    ///Display: Balling gun
    #[serde(rename = "100000073494")]
    N100000073494,
    ///Display: Barrel
    #[serde(rename = "100000073495")]
    N100000073495,
    ///Display: Blister
    #[serde(rename = "100000073496")]
    N100000073496,
    ///Display: Bottle
    #[serde(rename = "100000073497")]
    N100000073497,
    ///Display: Box
    #[serde(rename = "100000073498")]
    N100000073498,
    ///Display: Sachet
    #[serde(rename = "100000073547")]
    N100000073547,
    ///Display: Vial
    #[serde(rename = "100000073563")]
    N100000073563,
    ///Display: Pack
    #[serde(rename = "100000143555")]
    N100000143555,
}
impl MedicinalProductPackageType {
    pub fn as_code(&self) -> &'static str {
        match self {
            MedicinalProductPackageType::N100000073490 => "100000073490",
            MedicinalProductPackageType::N100000073491 => "100000073491",
            MedicinalProductPackageType::N100000073492 => "100000073492",
            MedicinalProductPackageType::N100000073493 => "100000073493",
            MedicinalProductPackageType::N100000073494 => "100000073494",
            MedicinalProductPackageType::N100000073495 => "100000073495",
            MedicinalProductPackageType::N100000073496 => "100000073496",
            MedicinalProductPackageType::N100000073497 => "100000073497",
            MedicinalProductPackageType::N100000073498 => "100000073498",
            MedicinalProductPackageType::N100000073547 => "100000073547",
            MedicinalProductPackageType::N100000073563 => "100000073563",
            MedicinalProductPackageType::N100000143555 => "100000143555",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/medicinal-product-package-type"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for MedicinalProductPackageType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "100000073490" => Ok(MedicinalProductPackageType::N100000073490),
            "100000073491" => Ok(MedicinalProductPackageType::N100000073491),
            "100000073492" => Ok(MedicinalProductPackageType::N100000073492),
            "100000073493" => Ok(MedicinalProductPackageType::N100000073493),
            "100000073494" => Ok(MedicinalProductPackageType::N100000073494),
            "100000073495" => Ok(MedicinalProductPackageType::N100000073495),
            "100000073496" => Ok(MedicinalProductPackageType::N100000073496),
            "100000073497" => Ok(MedicinalProductPackageType::N100000073497),
            "100000073498" => Ok(MedicinalProductPackageType::N100000073498),
            "100000073547" => Ok(MedicinalProductPackageType::N100000073547),
            "100000073563" => Ok(MedicinalProductPackageType::N100000073563),
            "100000143555" => Ok(MedicinalProductPackageType::N100000143555),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for MedicinalProductPackageType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

