// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: PriceComponentType
///Canonical URL: http://hl7.org/fhir/price-component-type
///Version: 5.0.0
///Title: Price Component Type
///Status: draft
///Codes indicating the kind of the price component.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PriceComponentType {
    ///Display: base price
    ///Definition: the amount is the base price used for calculating the total price before applying surcharges, discount or taxes.
    #[serde(rename = "base")]
    Base,
    ///Display: surcharge
    ///Definition: the amount is a surcharge applied on the base price.
    #[serde(rename = "surcharge")]
    Surcharge,
    ///Display: deduction
    ///Definition: the amount is a deduction applied on the base price.
    #[serde(rename = "deduction")]
    Deduction,
    ///Display: discount
    ///Definition: the amount is a discount applied on the base price.
    #[serde(rename = "discount")]
    Discount,
    ///Display: tax
    ///Definition: the amount is the tax component of the total price.
    #[serde(rename = "tax")]
    Tax,
    ///Display: informational
    ///Definition: the amount is of informational character, it has not been applied in the calculation of the total price.
    #[serde(rename = "informational")]
    Informational,
}
impl PriceComponentType {
    pub fn as_code(&self) -> &'static str {
        match self {
            PriceComponentType::Base => "base",
            PriceComponentType::Surcharge => "surcharge",
            PriceComponentType::Deduction => "deduction",
            PriceComponentType::Discount => "discount",
            PriceComponentType::Tax => "tax",
            PriceComponentType::Informational => "informational",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/price-component-type"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for PriceComponentType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "base" => Ok(PriceComponentType::Base),
            "surcharge" => Ok(PriceComponentType::Surcharge),
            "deduction" => Ok(PriceComponentType::Deduction),
            "discount" => Ok(PriceComponentType::Discount),
            "tax" => Ok(PriceComponentType::Tax),
            "informational" => Ok(PriceComponentType::Informational),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for PriceComponentType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

