// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: QuestionnaireItemOperator
///Canonical URL: http://hl7.org/fhir/questionnaire-enable-operator
///Version: 5.0.0
///Title: Questionnaire Item Operator
///Status: active
///The criteria by which a question is enabled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum QuestionnaireItemOperator {
    ///Display: Exists
    ///Definition: True if the determination of 'whether an answer exists for the question' is equal to the enableWhen answer (which must be a boolean).
    #[serde(rename = "exists")]
    Exists,
    ///Display: Equals
    ///Definition: True if at least one answer has a value that is equal to the enableWhen answer.
    #[serde(rename = "=")]
    Eq,
    ///Display: Not Equals
    ///Definition: True if no answer has a value that is equal to the enableWhen answer.
    #[serde(rename = "!=")]
    Ne,
    ///Display: Greater Than
    ///Definition: True if at least one answer has a value that is greater than the enableWhen answer.
    #[serde(rename = ">")]
    Gt,
    ///Display: Less Than
    ///Definition: True if at least one answer has a value that is less than the enableWhen answer.
    #[serde(rename = "<")]
    Lt,
    ///Display: Greater or Equals
    ///Definition: True if at least one answer has a value that is greater or equal to the enableWhen answer.
    #[serde(rename = ">=")]
    Ge,
    ///Display: Less or Equals
    ///Definition: True if at least one answer has a value that is less or equal to the enableWhen answer.
    #[serde(rename = "<=")]
    Le,
}
impl QuestionnaireItemOperator {
    pub fn as_code(&self) -> &'static str {
        match self {
            QuestionnaireItemOperator::Exists => "exists",
            QuestionnaireItemOperator::Eq => "=",
            QuestionnaireItemOperator::Ne => "!=",
            QuestionnaireItemOperator::Gt => ">",
            QuestionnaireItemOperator::Lt => "<",
            QuestionnaireItemOperator::Ge => ">=",
            QuestionnaireItemOperator::Le => "<=",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/questionnaire-enable-operator"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for QuestionnaireItemOperator {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "exists" => Ok(QuestionnaireItemOperator::Exists),
            "=" => Ok(QuestionnaireItemOperator::Eq),
            "!=" => Ok(QuestionnaireItemOperator::Ne),
            ">" => Ok(QuestionnaireItemOperator::Gt),
            "<" => Ok(QuestionnaireItemOperator::Lt),
            ">=" => Ok(QuestionnaireItemOperator::Ge),
            "<=" => Ok(QuestionnaireItemOperator::Le),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for QuestionnaireItemOperator {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

