// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: ResearchStudyReasonStopped
///Canonical URL: http://hl7.org/fhir/research-study-reason-stopped
///Version: 5.0.0
///Title: ResearchStudy Reason Stopped Code System
///Status: active
///Codes for why the study ended prematurely.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ResearchStudyReasonStopped {
    ///Display: Accrual Goal Met
    ///Definition: The study prematurely ended because the accrual goal was met.
    #[serde(rename = "accrual-goal-met")]
    AccrualGoalMet,
    ///Display: Closed due to toxicity
    ///Definition: The study prematurely ended due to toxicity.
    #[serde(rename = "closed-due-to-toxicity")]
    ClosedDueToToxicity,
    ///Display: Closed due to lack of study progress
    ///Definition: The study prematurely ended due to lack of study progress.
    #[serde(rename = "closed-due-to-lack-of-study-progress")]
    ClosedDueToLackOfStudyProgress,
    ///Display: Temporarily closed per study design
    ///Definition: The study prematurely ended temporarily per study design.
    #[serde(rename = "temporarily-closed-per-study-design")]
    TemporarilyClosedPerStudyDesign,
}
impl ResearchStudyReasonStopped {
    pub fn as_code(&self) -> &'static str {
        match self {
            ResearchStudyReasonStopped::AccrualGoalMet => "accrual-goal-met",
            ResearchStudyReasonStopped::ClosedDueToToxicity => "closed-due-to-toxicity",
            ResearchStudyReasonStopped::ClosedDueToLackOfStudyProgress => {
                "closed-due-to-lack-of-study-progress"
            }
            ResearchStudyReasonStopped::TemporarilyClosedPerStudyDesign => {
                "temporarily-closed-per-study-design"
            }
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/research-study-reason-stopped"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for ResearchStudyReasonStopped {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "accrual-goal-met" => Ok(ResearchStudyReasonStopped::AccrualGoalMet),
            "closed-due-to-toxicity" => {
                Ok(ResearchStudyReasonStopped::ClosedDueToToxicity)
            }
            "closed-due-to-lack-of-study-progress" => {
                Ok(ResearchStudyReasonStopped::ClosedDueToLackOfStudyProgress)
            }
            "temporarily-closed-per-study-design" => {
                Ok(ResearchStudyReasonStopped::TemporarilyClosedPerStudyDesign)
            }
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for ResearchStudyReasonStopped {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

