// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: SearchEntryMode
///Canonical URL: http://hl7.org/fhir/search-entry-mode
///Version: 5.0.0
///Title: Search Entry Mode
///Status: active
///Why an entry is in the result set - whether it's included as a match or because of an _include requirement, or to convey information or warning information about the search process.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SearchEntryMode {
    ///Display: Match
    ///Definition: This resource matched the search specification.
    #[serde(rename = "match")]
    Match,
    ///Display: Include
    ///Definition: This resource is returned because it is referred to from another resource in the search set.
    #[serde(rename = "include")]
    Include,
    ///Display: Outcome
    ///Definition: An OperationOutcome that provides additional information about the processing of a search.
    #[serde(rename = "outcome")]
    Outcome,
}
impl SearchEntryMode {
    pub fn as_code(&self) -> &'static str {
        match self {
            SearchEntryMode::Match => "match",
            SearchEntryMode::Include => "include",
            SearchEntryMode::Outcome => "outcome",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/search-entry-mode"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for SearchEntryMode {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "match" => Ok(SearchEntryMode::Match),
            "include" => Ok(SearchEntryMode::Include),
            "outcome" => Ok(SearchEntryMode::Outcome),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for SearchEntryMode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

