// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: StudyDesign
///Canonical URL: http://hl7.org/fhir/study-design
///Version: 5.0.0
///Title: Study Design
///Status: active
///This is a set of terms for study design characteristics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StudyDesign {
    ///Display: Interventional research
    ///Definition: A study design in which an independent variable (an exposure or intervention) is prospectively assigned or modified by the investigator to evaluate a response in the dependent variable (an effect or outcome).
    #[serde(rename = "SEVCO:01001")]
    Sevco01001,
    ///Display: Observational research
    ///Definition: A study design in which the independent variables (exposures or interventions) are not prospectively assigned or modified by the investigator.
    #[serde(rename = "SEVCO:01002")]
    Sevco01002,
    ///Display: Comparative study design
    ///Definition: A study design in which two or more groups are compared.
    #[serde(rename = "SEVCO:01010")]
    Sevco01010,
    ///Display: Non-comparative study design
    ///Definition: A study design with no comparisons between groups with different exposures and no comparisons between groups with different outcomes.
    #[serde(rename = "SEVCO:01023")]
    Sevco01023,
    ///Display: Population-based design
    ///Definition: A study design in which the unit of observation is a population or community.
    #[serde(rename = "SEVCO:01022")]
    Sevco01022,
    ///Display: Cross sectional data collection
    ///Definition: A study design process in which data is collected at a single point in time.
    #[serde(rename = "SEVCO:01027")]
    Sevco01027,
    ///Display: Longitudinal data collection
    ///Definition: A study design process in which data is collected at two or more points in time.
    #[serde(rename = "SEVCO:01028")]
    Sevco01028,
    ///Display: Primary data collection
    ///Definition: A study design process in which the data are recorded and collected during the study for the purpose of the same study.
    #[serde(rename = "SEVCO:01045")]
    Sevco01045,
    ///Display: Real world data collection
    ///Definition: A study design process in which the study data are obtained from a source of data collected during a routine process in the natural environment rather than using a process designed or controlled by the researcher.
    #[serde(rename = "SEVCO:01026")]
    Sevco01026,
    ///Display: Secondary data collection from prior research
    ///Definition: A study design process in which the data are collected from data obtained during a different study than the current study.
    #[serde(rename = "SEVCO:01049")]
    Sevco01049,
    ///Display: Secondary data collection from a registry
    ///Definition: A study design process in which the data are collected from a system organized to obtain and maintain uniform data for discovery and analysis, and this system is organized prior to the current study.
    #[serde(rename = "SEVCO:01042")]
    Sevco01042,
    ///Display: Multisite data collection
    ///Definition: A study design process in which data are collected from two or more geographic locations.
    #[serde(rename = "SEVCO:01051")]
    Sevco01051,
    ///Display: Quantitative analysis
    ///Definition: A study design process in which data are analyzed with mathematical or statistical methods and formulas.
    #[serde(rename = "SEVCO:01086")]
    Sevco01086,
    ///Display: Qualitative analysis
    ///Definition: A study design process in which data are analyzed, without primary reliance on mathematical or statistical techniques, by coding and organizing data to provide interpretation or understanding of experiences or hypotheses.
    #[serde(rename = "SEVCO:01087")]
    Sevco01087,
    ///Display: Blinding of study participants
    ///Definition: A study design process in which study participants are not informed of their intervention assignment.
    #[serde(rename = "SEVCO:01060")]
    Sevco01060,
    ///Display: Blinding of intervention providers
    ///Definition: A study design process in which the people administering the intervention are not informed of the intervention assignment.
    #[serde(rename = "SEVCO:01061")]
    Sevco01061,
    ///Display: Blinding of outcome assessors
    ///Definition: A study design process in which the people determining the outcome are not informed of the intervention assignment.
    #[serde(rename = "SEVCO:01062")]
    Sevco01062,
    ///Display: Blinding of data analysts
    ///Definition: A study design process in which the people managing or processing the data and statistical analysis are not informed of the intervention assignment.
    #[serde(rename = "SEVCO:01063")]
    Sevco01063,
    ///Display: Allocation concealment
    ///Definition: A study design process in which all parties influencing study enrollment and allocation to study groups are unaware of the group assignment for the study participant at the time of enrollment and allocation.
    #[serde(rename = "SEVCO:01064")]
    Sevco01064,
    ///Display: Multicentric
    ///Definition: A study design feature in which two or more institutions are responsible for the conduct of the study.
    #[serde(rename = "SEVCO:01043")]
    Sevco01043,
    ///Display: Includes patient-reported outcome
    ///Definition: A study design feature in which one or more outcomes are reported directly from the patient without interpretation by a clinician or researcher.
    #[serde(rename = "SEVCO:01052")]
    Sevco01052,
    ///Display: Includes patient-centered outcome
    ///Definition: A study design feature in which one or more measures are outcomes that patients directly care about, i.e. outcomes that are directly related to patients' experience of their life.
    #[serde(rename = "SEVCO:01053")]
    Sevco01053,
    ///Display: Includes disease-oriented outcome
    ///Definition: A study design feature in which one or more measures are outcomes that relate to a health or illness condition but are not outcomes which patients directly care about.
    #[serde(rename = "SEVCO:01054")]
    Sevco01054,
    ///Display: Includes process measure
    ///Definition: A study design feature in which one or more outcomes are actions or behaviors of a healthcare professional or care team.
    #[serde(rename = "SEVCO:01085")]
    Sevco01085,
    ///Display: Study Goal
    ///Definition: A study design feature specifying the intent of the study.
    #[serde(rename = "SEVCO:01089")]
    Sevco01089,
}
impl StudyDesign {
    pub fn as_code(&self) -> &'static str {
        match self {
            StudyDesign::Sevco01001 => "SEVCO:01001",
            StudyDesign::Sevco01002 => "SEVCO:01002",
            StudyDesign::Sevco01010 => "SEVCO:01010",
            StudyDesign::Sevco01023 => "SEVCO:01023",
            StudyDesign::Sevco01022 => "SEVCO:01022",
            StudyDesign::Sevco01027 => "SEVCO:01027",
            StudyDesign::Sevco01028 => "SEVCO:01028",
            StudyDesign::Sevco01045 => "SEVCO:01045",
            StudyDesign::Sevco01026 => "SEVCO:01026",
            StudyDesign::Sevco01049 => "SEVCO:01049",
            StudyDesign::Sevco01042 => "SEVCO:01042",
            StudyDesign::Sevco01051 => "SEVCO:01051",
            StudyDesign::Sevco01086 => "SEVCO:01086",
            StudyDesign::Sevco01087 => "SEVCO:01087",
            StudyDesign::Sevco01060 => "SEVCO:01060",
            StudyDesign::Sevco01061 => "SEVCO:01061",
            StudyDesign::Sevco01062 => "SEVCO:01062",
            StudyDesign::Sevco01063 => "SEVCO:01063",
            StudyDesign::Sevco01064 => "SEVCO:01064",
            StudyDesign::Sevco01043 => "SEVCO:01043",
            StudyDesign::Sevco01052 => "SEVCO:01052",
            StudyDesign::Sevco01053 => "SEVCO:01053",
            StudyDesign::Sevco01054 => "SEVCO:01054",
            StudyDesign::Sevco01085 => "SEVCO:01085",
            StudyDesign::Sevco01089 => "SEVCO:01089",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/study-design"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for StudyDesign {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "SEVCO:01001" => Ok(StudyDesign::Sevco01001),
            "SEVCO:01002" => Ok(StudyDesign::Sevco01002),
            "SEVCO:01010" => Ok(StudyDesign::Sevco01010),
            "SEVCO:01023" => Ok(StudyDesign::Sevco01023),
            "SEVCO:01022" => Ok(StudyDesign::Sevco01022),
            "SEVCO:01027" => Ok(StudyDesign::Sevco01027),
            "SEVCO:01028" => Ok(StudyDesign::Sevco01028),
            "SEVCO:01045" => Ok(StudyDesign::Sevco01045),
            "SEVCO:01026" => Ok(StudyDesign::Sevco01026),
            "SEVCO:01049" => Ok(StudyDesign::Sevco01049),
            "SEVCO:01042" => Ok(StudyDesign::Sevco01042),
            "SEVCO:01051" => Ok(StudyDesign::Sevco01051),
            "SEVCO:01086" => Ok(StudyDesign::Sevco01086),
            "SEVCO:01087" => Ok(StudyDesign::Sevco01087),
            "SEVCO:01060" => Ok(StudyDesign::Sevco01060),
            "SEVCO:01061" => Ok(StudyDesign::Sevco01061),
            "SEVCO:01062" => Ok(StudyDesign::Sevco01062),
            "SEVCO:01063" => Ok(StudyDesign::Sevco01063),
            "SEVCO:01064" => Ok(StudyDesign::Sevco01064),
            "SEVCO:01043" => Ok(StudyDesign::Sevco01043),
            "SEVCO:01052" => Ok(StudyDesign::Sevco01052),
            "SEVCO:01053" => Ok(StudyDesign::Sevco01053),
            "SEVCO:01054" => Ok(StudyDesign::Sevco01054),
            "SEVCO:01085" => Ok(StudyDesign::Sevco01085),
            "SEVCO:01089" => Ok(StudyDesign::Sevco01089),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for StudyDesign {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

