// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: SubscriptionStatus
///Canonical URL: http://hl7.org/fhir/subscription-status
///Version: 5.0.0
///Title: Subscription Status
///Status: active
///This codesystem defines a set of codes that can be used to filter Subscription triggers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SubscriptionStatus {
    ///Display: Requested
    ///Definition: The client has requested the subscription, and the server has not yet set it up.
    #[serde(rename = "requested")]
    Requested,
    ///Display: Active
    ///Definition: The subscription is active.
    #[serde(rename = "active")]
    Active,
    ///Display: Error
    ///Definition: The server has an error executing the notification.
    #[serde(rename = "error")]
    Error,
    ///Display: Off
    ///Definition: Too many errors have occurred or the subscription has expired.
    #[serde(rename = "off")]
    Off,
    ///Display: Entered in Error
    ///Definition: This subscription has been flagged as incorrect.
    #[serde(rename = "entered-in-error")]
    EnteredInError,
}
impl SubscriptionStatus {
    pub fn as_code(&self) -> &'static str {
        match self {
            SubscriptionStatus::Requested => "requested",
            SubscriptionStatus::Active => "active",
            SubscriptionStatus::Error => "error",
            SubscriptionStatus::Off => "off",
            SubscriptionStatus::EnteredInError => "entered-in-error",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/subscription-status"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for SubscriptionStatus {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "requested" => Ok(SubscriptionStatus::Requested),
            "active" => Ok(SubscriptionStatus::Active),
            "error" => Ok(SubscriptionStatus::Error),
            "off" => Ok(SubscriptionStatus::Off),
            "entered-in-error" => Ok(SubscriptionStatus::EnteredInError),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for SubscriptionStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

