// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: TitleType
///Canonical URL: http://hl7.org/fhir/title-type
///Version: 5.0.0
///Title: Title Type
///Status: active
///Used to express the reason and specific aspect for the variant title, such as language and specific language.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TitleType {
    ///Display: Primary title
    ///Definition: Main title for common use. The primary title used for representation if multiple titles exist.
    #[serde(rename = "primary")]
    Primary,
    ///Display: Official title
    ///Definition: The official or authoritative title.
    #[serde(rename = "official")]
    Official,
    ///Display: Scientific title
    ///Definition: Title using scientific terminology.
    #[serde(rename = "scientific")]
    Scientific,
    ///Display: Plain language title
    ///Definition: Title using language common to lay public discourse.
    #[serde(rename = "plain-language")]
    PlainLanguage,
    ///Display: Subtitle
    ///Definition: Subtitle or secondary title.
    #[serde(rename = "subtitle")]
    Subtitle,
    ///Display: Short title
    ///Definition: Brief title (e.g. 'running title' or title used in page headers)
    #[serde(rename = "short-title")]
    ShortTitle,
    ///Display: Acronym
    ///Definition: Abbreviation used as title
    #[serde(rename = "acronym")]
    Acronym,
    ///Display: Different text in an earlier version
    ///Definition: Alternative form of title in an earlier version such as epub ahead of print.
    #[serde(rename = "earlier-title")]
    EarlierTitle,
    ///Display: Different language
    ///Definition: Additional form of title in a different language.
    #[serde(rename = "language")]
    Language,
    ///Display: Different language derived from autotranslation
    ///Definition: Machine translated form of title in a different language, language element codes the language into which it was translated by machine.
    #[serde(rename = "autotranslated")]
    Autotranslated,
    ///Display: Human use
    ///Definition: Human-friendly title
    #[serde(rename = "human-use")]
    HumanUse,
    ///Display: Machine use
    ///Definition: Machine-friendly title
    #[serde(rename = "machine-use")]
    MachineUse,
    ///Display: Different text for the same object with a different identifier
    ///Definition: An alternative form of the title in two or more entries, e.g. in multiple medline entries
    #[serde(rename = "duplicate-uid")]
    DuplicateUid,
}
impl TitleType {
    pub fn as_code(&self) -> &'static str {
        match self {
            TitleType::Primary => "primary",
            TitleType::Official => "official",
            TitleType::Scientific => "scientific",
            TitleType::PlainLanguage => "plain-language",
            TitleType::Subtitle => "subtitle",
            TitleType::ShortTitle => "short-title",
            TitleType::Acronym => "acronym",
            TitleType::EarlierTitle => "earlier-title",
            TitleType::Language => "language",
            TitleType::Autotranslated => "autotranslated",
            TitleType::HumanUse => "human-use",
            TitleType::MachineUse => "machine-use",
            TitleType::DuplicateUid => "duplicate-uid",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/title-type"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for TitleType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "primary" => Ok(TitleType::Primary),
            "official" => Ok(TitleType::Official),
            "scientific" => Ok(TitleType::Scientific),
            "plain-language" => Ok(TitleType::PlainLanguage),
            "subtitle" => Ok(TitleType::Subtitle),
            "short-title" => Ok(TitleType::ShortTitle),
            "acronym" => Ok(TitleType::Acronym),
            "earlier-title" => Ok(TitleType::EarlierTitle),
            "language" => Ok(TitleType::Language),
            "autotranslated" => Ok(TitleType::Autotranslated),
            "human-use" => Ok(TitleType::HumanUse),
            "machine-use" => Ok(TitleType::MachineUse),
            "duplicate-uid" => Ok(TitleType::DuplicateUid),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for TitleType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

