// @generated by AtriusValueSetGen
// DO NOT EDIT MANUALLY

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use serde::{Deserialize, Serialize};

use super::super::super::{Boolean, Code, CodeableConcept, Coding, Element, Uri};

use super::super::super::string::String as FhirString;

///FHIR CodeSystem: WarningType
///Canonical URL: http://hl7.org/fhir/warning-type
///Version: 5.0.0
///Title: Warning Type
///Status: active
///Classification of warning type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WarningType {
    ///Display: Get medical advice/attention.
    ///Definition: Get medical advice/attention.
    #[serde(rename = "P313")]
    P313,
    ///Display: Get medical advice/attention if you feel unwell.
    ///Definition: Get medical advice/attention if you feel unwell.
    #[serde(rename = "P314")]
    P314,
    ///Display: Get immediate medical advice/attention.
    ///Definition: Get immediate medical advice/attention.
    #[serde(rename = "P315")]
    P315,
    ///Display: Specific treatment is urgent (see ... on this label).
    ///Definition: Specific treatment is urgent (see ... on this label).
    #[serde(rename = "P320")]
    P320,
    ///Display: Specific treatment (see ... on this label).
    ///Definition: Specific treatment (see ... on this label).
    #[serde(rename = "P321")]
    P321,
    ///Display: Specific measures (see ... on this label).
    ///Definition: Specific measures (see ... on this label).
    #[serde(rename = "P322")]
    P322,
    ///Display: Rinse mouth.
    ///Definition: Rinse mouth.
    #[serde(rename = "P330")]
    P330,
    ///Display: Do NOT induce vomiting.
    ///Definition: Do NOT induce vomiting.
    #[serde(rename = "P331")]
    P331,
    ///Display: Remove/Take off immediately all contaminated clothing.
    ///Definition: Remove/Take off immediately all contaminated clothing.
    #[serde(rename = "P361")]
    P361,
    ///Display: Wash contaminated clothing before reuse..
    ///Definition: Wash contaminated clothing before reuse.
    #[serde(rename = "P363")]
    P363,
}
impl WarningType {
    pub fn as_code(&self) -> &'static str {
        match self {
            WarningType::P313 => "P313",
            WarningType::P314 => "P314",
            WarningType::P315 => "P315",
            WarningType::P320 => "P320",
            WarningType::P321 => "P321",
            WarningType::P322 => "P322",
            WarningType::P330 => "P330",
            WarningType::P331 => "P331",
            WarningType::P361 => "P361",
            WarningType::P363 => "P363",
        }
    }
    pub fn system() -> &'static str {
        "http://hl7.org/fhir/warning-type"
    }
    pub fn version() -> Option<&'static str> {
        Some("5.0.0")
    }
    /// Convert this code into a FHIR `code` primitive (`Code = Element<String, Extension>`).
    ///
    /// Useful for elements like `Patient.gender` that are bound directly to a ValueSet and use
    /// the `code` datatype.
    pub fn to_code(self) -> Code {
        Element {
            id: None,
            extension: None,
            value: Some(self.as_code().to_string()),
        }
    }
    /// Convert this code into a FHIR `Coding` with `system` and (if available) `version` set.
    ///
    /// Useful for `Coding` fields and for inclusion inside `CodeableConcept.coding`.
    pub fn to_coding(self) -> Coding {
        let system: Uri = Element {
            id: None,
            extension: None,
            value: Some(Self::system().to_string()),
        };
        Coding {
            id: None,
            extension: None,
            system: Some(system),
            version: Self::version()
                .map(|v| FhirString {
                    id: None,
                    extension: None,
                    value: Some(v.to_string()),
                }),
            code: Some(self.to_code()),
            display: None,
            user_selected: Option::<Boolean>::None,
        }
    }
    /// Convert this code into a minimal `CodeableConcept` (with a single `coding`).
    ///
    /// This is especially useful for bound elements that use `CodeableConcept` (e.g.
    /// extensible bindings).
    pub fn to_codeable_concept(self) -> CodeableConcept {
        CodeableConcept {
            id: None,
            extension: None,
            coding: Some(vec![self.to_coding()]),
            text: None,
        }
    }
    /// Parse a code string into this enum.
    ///
    /// This is a convenience wrapper around the `TryFrom<&str>` implementation.
    pub fn try_from_code(code: &str) -> Result<Self, ()> {
        <Self as core::convert::TryFrom<&str>>::try_from(code)
    }
    /// Parse from a FHIR `code` primitive (`Code = Element<String, Extension>`).
    pub fn try_from_code_element(code: &Code) -> Result<Self, ()> {
        match code.value.as_deref() {
            Some(v) => Self::try_from_code(v),
            None => Err(()),
        }
    }
}
impl core::convert::TryFrom<&str> for WarningType {
    type Error = ();
    fn try_from(s: &str) -> Result<Self, <Self as core::convert::TryFrom<&str>>::Error> {
        match s {
            "P313" => Ok(WarningType::P313),
            "P314" => Ok(WarningType::P314),
            "P315" => Ok(WarningType::P315),
            "P320" => Ok(WarningType::P320),
            "P321" => Ok(WarningType::P321),
            "P322" => Ok(WarningType::P322),
            "P330" => Ok(WarningType::P330),
            "P331" => Ok(WarningType::P331),
            "P361" => Ok(WarningType::P361),
            "P363" => Ok(WarningType::P363),
            _ => Err(()),
        }
    }
}
impl core::fmt::Display for WarningType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_code())
    }
}

